### ISSUE TITLE
mono2 branch doesn't work under mono with 4.0 profile

### ISSUE THREAD

**Issue by yojimbo87** [DotNetOpenAuth/DotNetOpenAuth#10]
I have tried to build mono2 branch (on VS 2008, .net 3.5) and referenced DotNetOpenAuth.dll within ASP.NET MVC 2 application running on mono from master branch (version 2.11, default profile is 4.0), but I'm getting [this](https://gist.github.com/794732) exception during authentication.

**Comment by AArnott** [comment]
This is a bug in mono.  Please file the bug there.
