### ISSUE TITLE
OAuth 2 support

### ISSUE THREAD

**Issue by oyvindkinsey** [DotNetOpenAuth/DotNetOpenAuth#11]
What is the current status?

Could this issue be used to track the status of the OAuth 2 support?

**Comment by AArnott** [comment]
DNOA currently implements draft 10 of the spec.  Draft 12 is the latest version of the spec.  So we're a draft or two behind at the moment.

**Comment by davidwaters** [comment]
Is the current implementation of draft 10 stable and reliable? I am interested in using this for production application and I'm a little scared by the CTP disclaimer. Do you have a time frame for merging this into stable?

Thanks.

**Comment by AArnott** [comment]
No further work is planned until OAuth 2.0 is final.  Keeping up with the various drafts and all their breaking changes takes too much wasted effort.
I believe the current draft 10 implementation is decent, but security reviews only happen after a spec is finalized, so no level of assurance is promised.

**Comment by AArnott** [comment]
Draft 15 is out, and allegedly nearing the final stages.  I expect to resume work to bring DotNetOpenAuth up to the latest draft soon.

**Comment by awimsatt** [comment]
I noticed that the code in github is more recent then the available download of the CTP on http://www.dotnetopenauth.net/  The code includes a fix that I'm waiting on.  Would you consider releasing an update to the CTP or providing compiled DLL's in the git repository.  I tried compiling the code myself, but I can't get it to sign correctly.

**Comment by AArnott** [comment]
The latest version of the OAuth2 branch is always available on our TeamCity continuous integration server:
http://teamcity.dotnetopenauth.net/viewType.html?buildTypeId=bt58&tab=buildTypeStatusDiv

That said, do so at your own risk.  The OAuth2 branch is _not stable_, and currently is an implementation of a blend of drafts of the OAuth 2 spec.  It may not be secure, it may not interop well with others.

A new CTP will be released when we feel better about the state of the branch.

**Comment by AArnott** [comment]
Closing this issue as the Hoover milestone tracks overall progress to full OAuth2 support.
