### ISSUE TITLE
schemeField is null on Mono (NonPathCompressingUriParser.Initialize)

### ISSUE THREAD

**Issue by merarischroeder** [DotNetOpenAuth/DotNetOpenAuth#111]
I'm getting a null reference error caused in NonPathCompressingUriParser.Initialize. The only suspect was schemeField, which relies on the m_Scheme private field. It appears that the name of that private field is different under Mono - "scheme_name", so how about you add in some extra code to handle that case - thanks!

internal void Initialize(bool hideNonStandardScheme) {
    if (schemeField == null) {
            schemeField = typeof(UriParser).GetField("m_Scheme", BindingFlags.NonPublic | BindingFlags.Instance);
    }
    if (schemeField == null) {
            schemeField = typeof(UriParser).GetField("scheme_name", BindingFlags.NonPublic | BindingFlags.Instance);
    }

...

}

**Comment by AArnott** [comment]
BTW, am I to understand that DNOA works on mono lately?  Has mono improved to such a point?  What branch/version of DNOA were you running?

**Comment by merarischroeder** [comment]
Thanks :)

As I was waking up this morning, I thought it would be better to source private field names from configuration (whenever you are looking up a private field [it looks like this is the only case from what I could find]), but this will certainly do for now.

I complied against the current trunk. Haven't got it completely working yet. I'm using xsp as the server (comes with mono, and it's like cassini).

Current problem: "System.UriFormatException: http://localhost/" (Note: I changed the code to add the Uri, to help me debug).

(at DotNetOpenAuth.OpenId.UriIdentifier..ctor (System.String uri, Boolean requireSslDiscovery) [0x00000] in <filename unknown>:0 
  at DotNetOpenAuth.OpenId.UriIdentifier..ctor (System.String uri) [0x00000] in <filename unknown>:0 
  at DotNetOpenAuth.OpenId.Identifier.Parse (System.String identifier, Boolean serializeExactValue) [0x00000] in <filename unknown>:0 
  at DotNetOpenAuth.OpenId.Identifier.Parse (System.String identifier) [0x00000] in <filename unknown>:0 
  at DotNetOpenAuth.OpenId.Identifier.op_Implicit (System.String identifier) [0x00000] in <filename unknown>:0 
  at DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty..cctor () [0x00000] in <filename unknown>:0 )

I'm working on it now, the url will be available most of the time, I only take it down while upgrading: http://merevik.com:8080/Account/LogOn

**Comment by merarischroeder** [comment]
(I'm using VS 2010, MVC3, .Net 4 [Release version of DNOA], and deploying to Ubuntu Mono)

I'll keep slogging it out, for now. If it gets too anoying, I'll probably just deploy to MS .NET.

**Comment by AArnott** [comment]
Well thanks very much for working on this.  A lot of people want DNOA to work on mono but I just haven't had the time and resources for it.  Please consider forking the project on github and sending a pull request when you have fixes to share.  Otherwise just keep filing distinct issues for whatever you find with the fixes you've developed.

As for the UriFormatException... I don't know why mono thinks that one is invalid.  It looks valid to me.

**Comment by merarischroeder** [comment]
I've just taken out a try block for the TryCanonicalize method, so I can track it down...

**Comment by merarischroeder** [comment]
I got some more information - this doesn't make sense to me:

DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty ---> System.Exception: URI: dnoarthttp://localhost/ - 
- System.UriFormatException: The argument Uri's scheme does not match at 

where does "dnoarthttp://localhost/" come from?

Appears to change in NormalSchemeToSpecialRoundTrippingScheme

**Comment by merarischroeder** [comment]
Disabling the section as shown (just below here), got me much further, now I'm stuck on a web.config read error

static UriIdentifier() {
            // Our first attempt to handle trailing periods in path segments is to leverage
            // full trust if it's available to rewrite the rules.
            // In fact this is the ONLY way in .NET 3.5 (and arguably in .NET 4.0) to send
            // outbound HTTP requests with trailing periods, so it's the only way to perform
            // discovery on such an identifier.
            //try {
            //    UriParser.Register(roundTrippingHttpParser, "dnoarthttp", 80);
            //    UriParser.Register(roundTrippingHttpsParser, "dnoarthttps", 443);
            //    UriParser.Register(publishableHttpParser, "dnoahttp", 80);
            //    UriParser.Register(publishableHttpsParser, "dnoahttps", 443);
            //    roundTrippingHttpParser.Initialize(false);
            //    roundTrippingHttpsParser.Initialize(false);
            //    publishableHttpParser.Initialize(true);
            //    publishableHttpsParser.Initialize(true);
            //    schemeSubstitution = true;
            //    Logger.OpenId.Debug(".NET Uri class path compression overridden.");
            //    Reporting.RecordFeatureUse("FullTrust");
            //} catch (SecurityException) {
            //    // We must be running in partial trust.  Nothing more we can do.
            //    Logger.OpenId.Warn("Unable to coerce .NET to stop compressing URI paths due to partial trust limitations.  Some URL identifiers may be unable to complete login.");
                Reporting.RecordFeatureUse("PartialTrust");
            //}
        }

**Comment by merarischroeder** [comment]
Current problem:

Unrecognized attribute 'enabled'. (/root/merevikmvc/Code/Deploy/Web.config line 1)

Description: HTTP 500. Error processing request.

Stack Trace:

System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'enabled'. (/root/merevikmvc/Code/Deploy/Web.config line 1)
at System.Configuration.ConfigurationElement.DeserializeElement (System.Xml.XmlReader,bool) <0x00d07>
at System.Configuration.ConfigurationSection.DoDeserializeSection (System.Xml.XmlReader) <0x0021d>
at System.Configuration.ConfigurationSection.DeserializeSection (System.Xml.XmlReader) <0x00013>
at System.Configuration.Configuration.GetSectionInstance (System.Configuration.SectionInfo,bool) <0x002fb>

**Comment by merarischroeder** [comment]
removed <defaultProxy  enabled="true" /> from web.config

now current problem is:
The source sequence is empty

Description: HTTP 500. Error processing request.

Stack Trace:

System.InvalidOperationException: The source sequence is empty
  at System.Linq.Enumerable.First[IAuthenticationRequest](IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty.CreateRequest (DotNetOpenAuth.OpenId.Identifier userSuppliedIdentifier) [0x00000] in <filename unknown>:0

**Comment by merarischroeder** [comment]
- Removed (defaultProxy  enabled="true"/) from web.config

**Comment by merarischroeder** [comment]
System.InvalidOperationException: The source sequence is empty - possibly caused by my removal of defaultProxy...

**Comment by merarischroeder** [comment]
Just seen there is a mono2 branch, I might have a look at the differences

**Comment by AArnott** [comment]
The mono2 branch should work, but its code is quite old.
