### ISSUE TITLE
Bug in DotNetOpenAuth 4 stable version

### ISSUE THREAD

**Issue by joaoasrosa** [DotNetOpenAuth/DotNetOpenAuth#120]
Hi.

In my production server I try to use the latest stable version and got this error:

"Message: Unable to cast object of type 'DotNetOpenAuth.OpenId.Behaviors.AXFetchAsSregTransform' to type 'DotNetOpenAuth.OpenId.RelyingParty.IRelyingPartyBehavior'.;
InnerException: Sem inner exception.;
Source: DotNetOpenAuth.Core;
StackTrace:    at DotNetOpenAuth.Configuration.TypeConfigurationElement`1.CreateInstance(T defaultValue, Boolean allowInternals)
   at DotNetOpenAuth.Configuration.TypeConfigurationCollection`1.&lt;&gt;c__DisplayClass4.&lt;CreateInstances&gt;b__2(TypeConfigurationElement`1 element)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty..ctor(ICryptoKeyStore cryptoKeyStore, INonceStore nonceStore)
   at DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty..ctor()"

If I use the previous stable version the same code works.

I'm using a shared host, in ASP.NET 4 Classic mode.

**Comment by AArnott** [comment]
This looks like a bug in your setup.  There is no  DotNetOpenAuth.OpenId.Behaviors.AXFetchAsSregTransform type in DNOA 4.0.  That type only exists in DNOA v3.x.  The new type is DotNetOpenAuth.OpenId.RelyingParty.Behaviors.AXFetchAsSregTransform.  Please update your code (including possibly web.config file) to reference the new type and I think this problem will go away for you.

**Comment by joaoasrosa** [comment]
Yes it's my fault.
I forget to look to .config file... :(

Sorry to waste your time!
