### ISSUE TITLE
Compilation bug with DotNetOpenAuth.Core

### ISSUE THREAD

**Issue by psmoak** [DotNetOpenAuth/DotNetOpenAuth#123]
When attempting to build TestWeb and InfoCardRelyingParty sample websites I receive the error below and the build fails. All other projects build correctly.

Could not load file or assembly 'DotNetOpenAuth.Core, Version=4.1.0.0, Culture=neutral, PublicKeyToken=2780ccd10d57b246' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by AArnott** [comment]
This is because when build DNOA with the official public key you must register that key for skip verification in order to build and use it.

Why do you need to build the library?

**Comment by dstj** [comment]
I know this is a year old post, but I had the same issue today, so I thought I'd update the answer by saying _how_ to do it.

Note: I used DotNetOpenAuth's v4.0.30319 source code from the GitHub repo.

Open the Visual Studio Tools Command Prompt as Admin.

You can find (confirm) the the public key's token with this:
`C:\Dev\github\DotNetOpenAuth\bin\v4.0\Debug>sn -t ..\..\..\src\official-build-key.pub`

You'll get `Public key token is 2780ccd10d57b246`

Then run 
`C:\Dev\github\DotNetOpenAuth\bin\v4.0\Debug>sn -Vr *,2780ccd10d57b246`

This StackOverflow post also helped.
http://stackoverflow.com/questions/13060684/dotnetopenauth-compiles-after-modifications-but-throws-runtime-exception-when-ru

## 

As for Andrew's question, I want to built the library to understand why I get this exception while trying to create a simple OpenId RP / Provider scenario. It must be me not using the library correctly, but the exception message really isn't helping me much...

```
[InvalidOperationException: Sequence contains no elements]
   System.Linq.Enumerable.First(IEnumerable`1 source) +514
   DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty.CreateRequest(Identifier userSuppliedIdentifier) +128

[ProtocolException: No OpenID endpoint found.]
   DotNetOpenAuth.OpenId.RelyingParty.OpenIdRelyingParty.CreateRequest(Identifier userSuppliedIdentifier) +245
```

**Comment by AArnott** [comment]
Thanks for sharing back. The error you're seeing is because the URL entered
is not valid Open ID. Or perhaps a server is down. In general that
exception means the Open ID could not be resolved and is usually the result
user error. Remember when you're looking at the error to notice the last
exception rather than the first exception, as the last exception has the
most correct high-level message for the user to see and is the exception
that your website would actually catch.

**Comment by dstj** [comment]
My pleasure.

Actually, it was that `localhost` had not been whitelisted in the client's Web.config...

The actual exception (`The URL 'https://localhost/AuthProvider/openid' is rated unsafe and cannot be requested this way.`) was caught in `DotNetOpenAuth\src\DotNetOpenAuth.OpenId.RelyingParty\OpenId\RelyingParty\AuthenticationRequest.cs` at line 376 but was not rethrown:

```
            } catch (ProtocolException ex) {
                Logger.Yadis.ErrorFormat("Error while performing discovery on: \"{0}\": {1}", userSuppliedIdentifier, ex);
                serviceEndpoints = Enumerable.Empty<IdentifierDiscoveryResult>();
            }
```

so this code in `OpenIdRelyingParty.cs` failed by received an unexplained empty sequence

```
        public IAuthenticationRequest CreateRequest(Identifier userSuppliedIdentifier) {
            Requires.NotNull(userSuppliedIdentifier, "userSuppliedIdentifier");
            Contract.Ensures(Contract.Result<IAuthenticationRequest>() != null);
            try {
                return this.CreateRequests(userSuppliedIdentifier).First();
            } catch (InvalidOperationException ex) {
                throw ErrorUtilities.Wrap(ex, OpenIdStrings.OpenIdEndpointNotFound);
            }
        }
```

Granted, I could probably have figured it out by plugging in Log4Net, but I sometimes like code-debugging better :)
