### ISSUE TITLE
Compilation errors relating comments

### ISSUE THREAD

**Issue by axefrog** [DotNetOpenAuth/DotNetOpenAuth#13]
When trying to compile DotNetOpenAuth, I get a lot of errors complaining that the XML comments for a bunch of the classes don't start with exactly the right text. I couldn't figure out how to turn off this requirement in Visual Studio...

**Comment by AArnott** [comment]
I need you to provide more information such as what branch you're on and configuration you're building, and preferably actual error messages from your build log.  Please re-open with details.
