### ISSUE TITLE
FacebookClient error when redirect_uri includes querystrings

### ISSUE THREAD

**Issue by benfoster** [DotNetOpenAuth/DotNetOpenAuth#139]
Ref: https://github.com/AArnott/dotnetopenid/blob/master/src/DotNetOpenAuth.AspNet/Clients/OAuth2/FacebookClient.cs

When requesting the Access Token, if the redirect_uri includes querystring parameters, we get the following error:

> The remote server returned an error: (400) Bad Request.

According to the spec (I think) encoded parameters should be supported in the redirect endpoint uri, but clearly this does not seems to be the case for Facebook or Google.

To work around this with a GoogleOAuthClient I created, in `GetServiceLoginUrl` we only send everything up to the path segment of the redirect url. We then encode the query portion and send this in the state parameter:

```
        builder.AppendQueryArgs(
            new Dictionary<string, string> {
                { "client_id", this.clientId },
                { "scope", "https://www.googleapis.com/auth/userinfo.profile" },
                { "response_type", "code" },
                { "redirect_uri", returnUrl.GetLeftPart(UriPartial.Path) },
                { "state", HttpUtility.UrlEncode(returnUrl.Query) }
            });
```

We have to do the same in `QueryAccessToken` (not including any querystrings):

```
    protected override string QueryAccessToken(Uri returnUrl, string authorizationCode) {
        var entity =
            UriBuilderExtensions.CreateQueryString(
                new Dictionary<string, string> {
                    { "client_id", this.clientId },
                    { "redirect_uri", returnUrl.GetLeftPart(UriPartial.Path) },
                    { "client_secret", this.clientSecret },
                    { "code", authorizationCode },
                    { "grant_type", "authorization_code" },
                });
```

Ben

**Comment by AArnott** [comment]
Thanks for sharing.  The encoding should be right, so I'm very surprised
that Google and Facebook reject these.  I heard only a couple days ago that
Facebook is ok with it so long as the encoding uses capital hexidecimal
letters instead of lowercase ones.  I'll look into that possibility before
applying your suggested change.

## 

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by benfoster** [comment]
Hi Andrew,
Facebook was the only site that _technically_ had a problem. However, the issue with Google is that the callback URL you specify when setting up your App must explicitly match the URL passed as the redirect_url. Obviously this is a problem for dynamic querystrings such as return urls.

**Comment by thejoshcrawford** [comment]
I am having this same issue with Google. Google requires the exact return url (including query strings) to be registered with the app. However DNOA requires the dynamic session id which cannot be added to Google's list of return urls.

**Comment by DavidChristiansen** [comment]
Please advise if this is still a relevant issue. If not please can you close the ticket.
