### ISSUE TITLE
Reporting hangs (deadlocks) when under stress

### ISSUE THREAD

**Issue by jondot** [DotNetOpenAuth/DotNetOpenAuth#15]
This is _probably_ related to reporting.
Here are some stack traces from 3 threads at time of hang.

https://gist.github.com/837338

**Comment by AArnott** [comment]
I've written some stress tests and I haven't been able to reproduce the problem.  The callstacks also don't immediately suggest a cause.  Can you please reproduce the problem and then capture a minidump of the process and make it available so we can see the callstacks for all the active threads?

**Comment by jondot** [comment]
I'll try it out. since its 1am here i'll only be able to start tomorrow :).

to elaborate on my test rig
6-7 browsers automated by selenium, doing RP-OP login concurrently, each running login-logout 1000 times.
overall takes 10-15min to get it to hang, all browsers hang, and OP still operable.
RP had reporting turned on, OP off.
RP is in dumb mode
