### ISSUE TITLE
IProviderApplicationStore is missing from DotNetOpenAuth.OpenId.Provider

### ISSUE THREAD

**Issue by frostshoxx** [DotNetOpenAuth/DotNetOpenAuth#150]
Hi there,

I have developed a login system on one of my web apps using DotNetOpenAuth.OpenId.

Since it will be ran on some kind of web farm platform, so I had to store the nonce key stuffs into the DB. So I had to use IProviderApplicationStore to do that.

However, with the latest version of DotNetOpenAuth, I can no longer create a class out of interface IProviderApplicationStore.

Are there any updates somewhere between version 2ish to this latest one that make this interface obsolete? If so, please advise on what am I supposed to replace it with the old implementation.

Thank you,

Patt

**Comment by AArnott** [comment]
In DNOA v4 the interface you should implement is now called `IOpenIdApplicationStore`.
