### ISSUE TITLE
DotNetOpenAuth.AspNet does not work for Asp.Net MVC scenarios

### ISSUE THREAD

**Issue by godspeedmai** [DotNetOpenAuth/DotNetOpenAuth#154]
IAuthenticationClient.RequestAuthentication implementation redirects the response to the service server at once, and there is no service url exposure, which does not work for Asp.NET MVC scenarios since MVC needs the RedirectResult returned to the view from the controller. 

Wish the component supports Asp.NET MVC very soon! 

Thanks,

**Comment by AArnott** [comment]
Thanks for your feedback.  I've passed it on to the folks who own this assembly.  That said, depending on what you're using this assembly for, you could try calling into DotNetOpenAuth directly (the DNOA.AspNet assembly is just a facade) and  DNOA itself is more MVC friendly.

**Comment by AArnott** [comment]
Sadly, since this has shipped in ASP.NET, I don't think we're going to fix it. But it does actually work just fine in MVC. Call it, and you'll see.
