### ISSUE TITLE
How to set 'state' parameter in WebServerClient class.

### ISSUE THREAD

**Issue by gekiss** [DotNetOpenAuth/DotNetOpenAuth#162]
In Oauth2 Access Google API Return URL must match with the input return URL. To send the context information is necessary to use a parameter 'state'.
When I use own AuthorizationTracker in WebServerClient class I not found a way to set 'state' parameter.

**Comment by AArnott** [comment]
The state parameter is primarily intended to mitigate XSRF and other attacks by being some opaque value that the client will recognize.  Can you store the state you need in a cookie, or as part of your callback URL?

**Comment by AArnott** [comment]
BTW, filing issues isn't appropriate for asking questions.  Please direct questions to dotnetopenid@googlegroups.com

**Comment by gekiss** [comment]
My state is giud type. I keep own state in Cookies. Store it in a callback URL work with WindowsLive and Facebook, but not in Google APIs. In the google Oauth2 forum i found that nead use a 'state' parameter. 
https://groups.google.com/forum/?fromgroups#!searchin/oauth2-dev/Wildcards/oauth2-dev/885I1MQrCjo/zy-CUKPdpNsJ

When I set AuthorizationTracker in DotNetOpenAuth.OAuth2.WebServerClient class not posible set 'state' parameter. Could you expand AuthorizationTracker class with the possibility setting a 'state' parameter
