### ISSUE TITLE
Why is Messaging/IncomingWebResponse.GetSnapshot marked as internal?

### ISSUE THREAD

**Issue by matejskubic** [DotNetOpenAuth/DotNetOpenAuth#165]
Why is Messaging/IncomingWebResponse.GetSnapshot marked as internal?

https://github.com/AArnott/dotnetopenid/blob/15f234f335ab7cdbcb14cc25a97f5dba22c7c663/src/DotNetOpenAuth.Core/Messaging/IncomingWebResponse.cs#L176

**Comment by AArnott** [comment]
Because it's not meant for external consumption.  Please direct questions to dotnetopenid@googlegroups.com rather than opening issues with the project till you have a bug report.  Thanks.
