### ISSUE TITLE
Bug fixing introduced a backward compatibility issue

### ISSUE THREAD

**Issue by NelsonReis** [DotNetOpenAuth/DotNetOpenAuth#169]
When fixing a bug in the commit below, a method was removed that broke backward compatibility:
https://github.com/DotNetOpenAuth/DotNetOpenAuth/commit/053202fa1fa6e875792a1bd99171eff7c6e99930

Is it possible to reintroduce the parameterless `VerifyAuthentication()` method?

**Comment by DavidChristiansen** [comment]
Please advise if this is still a relevant issue. If not please can you close the ticket.

**Comment by NelsonReis** [comment]
Yeah, not relevant anymore. Thanks.
