### ISSUE TITLE
Replace log4net dependency with common.logging

### ISSUE THREAD

**Issue by DavidChristiansen** [DotNetOpenAuth/DotNetOpenAuth#172]
Rather than having a dependency on log4net, I reckon we should build against common.logging which allows the end user to choose which logging framework they want to implement.

**Comment by DavidChristiansen** [comment]
Samples will continue to use log4net, with common.logging instructed to use the log4net adapter.

**Comment by rcollette** [comment]
Agree!  I was just looking at common.logging and it is active.

**Comment by AArnott** [comment]
I like this idea too.

**Comment by AArnott** [comment]
If anyone can send a pull request against the master branch, I'd appreciate it.

**Comment by DavidChristiansen** [comment]
This is being closed as I have replaced logging with a logging framework independent solution
