### ISSUE TITLE
Log XRDS response

### ISSUE THREAD

**Issue by rcollette** [DotNetOpenAuth/DotNetOpenAuth#180]
Include the raw XRDS raw response in log files.   Useful for troubleshooting and protocol comprehension.   Server to server (direct) communication can be difficult to "view" especially when operating in hosted environments.

**Comment by AArnott** [comment]
Hmmm... I can't think of any point where DNOA itself serves XRDS to the client. Can you remind me?

**Comment by rcollette** [comment]
Not directly but it does redirect/transfer to it and I found it confusing to figure out.   Of course with time I realized that it does so in response to the presence of the header.  I've become busy again and haven't had time to work on the xrds module but that will definitely log the redirect/transfer.

Sent from my Droid Charge on Verizon 4G LTE

------Original Message------
