### ISSUE TITLE
DNOA should send credentials not only when getting a 401

### ISSUE THREAD

**Issue by manfredsteyer** [DotNetOpenAuth/DotNetOpenAuth#185]
As discussed at [1], DNOA always tries to send a message without credentials and when the server sends back a 401 it re-sends the message with credentials. This leads to interop-problem with, for instance, google, as google is responding with a 400 (and not 401) in such cases.

This seems to be due to the fact, that DNOA uses HttpWebRequest which behaves this way.

8<----------

Suggestions to solve this issue:
1. Use an alternative to HttpWebRequest (seems to be a lot of work)
2. Send credentials within the payload instead of using HTTP BASIC. 

The second suggestion has several advantages: 

a) It's easy to implement
b) It's conform to oauth
c) It also prevents the issue that IIS tries to check credentials, passed using HTTP BASIC, against the AD when Authentication is activated within the IIS-configuration.

Perhaps we could create a flag "PassCredentialsWithinPayload".

As an alternative to that, we could allow the user to pass custom parameters within the payload.

8<----------

[1] https://groups.google.com/forum/?fromgroups#!topic/dotnetopenid/ibzRfE4TpB0

**Comment by jamesandersen** [comment]
This issue relates to issue #195

**Comment by AArnott** [comment]
Fixed by 84ef4b7436
