### ISSUE TITLE
Resource Owner Password Credentials Grant / Refresh Token / Client_id

### ISSUE THREAD

**Issue by ghost** [DotNetOpenAuth/DotNetOpenAuth#192]
In the Resource Owner Password Credentials Grant I can get a Refresh Token back from the Authorization Server. This is working fine with DNOA. I don't need to specify the client (client_id / client_secret)

When I try to use the Refresh token, DNOA wants to have a client_id? I think this is an bug.

**Comment by AArnott** [comment]
The spec suggests (to me) that client authentication is required for both steps. 
http://tools.ietf.org/id/draft-ietf-oauth-v2-31.html#rfc.section.4.3.1
