### ISSUE TITLE
OAuth2 WebServerClient Fails with Salesforce (but with workaround)

### ISSUE THREAD

**Issue by sassame** [DotNetOpenAuth/DotNetOpenAuth#204]
Not sure if this is a bug or not, but I only figured out the work around after tracing through the code for an hour, so it seems like it.  Basically, the WebServerClient fails calling against the Salesforce OAuth2 service with this configuration:

var sfClient = new WebServerClient(
                    sfServer,
                    clientIdentifier: "3dasfasdfjhasdfjhgsafdkjhgadfkjhgsfkjaghdfkjagfkjagfkajgfkjagfasd",
                    clientSecret: "123412351234");

but works with this:

static Salesforce() {
            Client = new WebServerClient(authServerDescription,
                "ASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFASDFSDAF",
                ClientCredentialApplicator.PostParameter("1234123413412341324124"));
        }

Looks to be a bug in the code that sets the default applicator that it uses the network applicator instead of the post applicator...but maybe that's as designed?

**Comment by AArnott** [comment]
The `NetworkCredentialApplicator` seems faulty as several people have pointed this out. This issue will track fixing it.
