### ISSUE TITLE
HandleTokenRequest - HttpRequestMessage Support

### ISSUE THREAD

**Issue by holyprin** [DotNetOpenAuth/DotNetOpenAuth#210]
As it currently sits WebApi does not require the use of MVC to run.  With that said, HttpContext is now removed from Request.Properties in those "Self Hosted" solutions.

Adding overloads that handle HttpRequestMessages in all the key locations would go a long way in future proofing DNOA hosting solutions.

**Comment by AArnott** [comment]
Fixed by ba720fb8879

**Comment by holyprin** [comment]
That fix was a month ago and does not apply to self hosted web environments. Also need httprequestmessage to be a parameter of HandleRequestToken in the authorization server.  As it sits you can only self host the resource server side of the coin.

**Comment by AArnott** [comment]
Good point, @holyprin. I have applied an additional fix to the v4.1 branch that adds the requested overload.
