### ISSUE TITLE
Issue with callback url

### ISSUE THREAD

**Issue by AnalogJ** [DotNetOpenAuth/DotNetOpenAuth#216]
When returning back to my MVC3 from DotNetOpenAuth initialized request I'm getting urls like the following:

http://www.example.com/(F(dJ-sgPO_RI4O_v5SrXyHtDy4vXKMOAvs7eLLDFH8115vwgSoksTsUmQnY5iDhpTnwGMqbJKYvpAIz76F-KgXljPxCzxA6FBaodrwbcfnyfFd_7MUL_ACf-toBTQEyIVUz9kzAsWd5lKG59I5AADHMoaqbVM8A1))/Area/Controller/Action

With further testing it seems that MVC3 will handle urls with the following format:
http://www.example.com/(X())/Area/Controller/Action
even though they are not valid. This issue also only seems to occur when authenticating with an Ipad,(I think it may happen with other mobile devices but I'm not sure)

I'm not sure if this is the right place to ask, but have you seen this issue before/is this a known problem?

**Comment by AArnott** [comment]
I don't follow what the "problem" is.  The URL is perfectly valid. If you're not expecting the parenthetical segment of the path, that's what ASP.NET uses to track session state when in cookieless mode.  Check your web.config file for cookieless settings.  It has nothing to do with DotNetOpenAuth either way.
