### ISSUE TITLE
Forwarding OpenId Responses

### ISSUE THREAD

**Issue by SLaks** [DotNetOpenAuth/DotNetOpenAuth#228]
We have an existing non-wildcard OpenId realm which we now need to use with multiple domain names.

To make this possible, I have a redirector endpoint on the production domain (which matches the existing realm) that forwards the response to a URL from the `path` argument in the `return_to`'s querystring.

However, it is impossible to use DotNetOpenAuth in the receiving end on the other domain, because it (correctly) fails to validate the `return_to`.

What is the best way to handle this situation? (we can't switch to a wildcard realm)

For now, I modified DotNetOpenAuth to allow me to disable `return_to` validation for these cases.

To maintain security, I do the following:
- On the redirector endpoint (in the realm's domain name)  :
  - Check that the hostname in the `path` argument (which we forward the request to) is a subdomain of our domain name (or localhost)
  - Do the usual `return_to` validation against the current URL (copied from DNOA source). (this can only be done for successful responses)
  - Strip our `path` argument from the querystring we send to the final endpoint)
- On the receiving endpoint (in a different domain name)
  - Skip all of this logic (and do DNOA's built-in realm validation) if the current hostname does match the realm (the same codebase runs on both domain names)
  - Construct the URL we would send to the realm's server to redirect to the requested URL (including all querystring parameters received in this request, as well as the `path` parameter for the redirector), and verify the received `return_to` against that
  - Check that the `path` parameter from inside the `return_to` URL (which was sent to the redirector and removed from our querystring) matches our current URL.

Did I create any security issues here?

Can DNOA be modified to support this natively?

The ideal solution would be a method in `OpenIdRelyingParty` called `ForwardRequest()` which I would call on the redirector, along with configuration in the `OpenIdRelyingParty` specifying the URL for the redirector (which would be used by `CreateRequest()`) and a whitelist of valid target Uris.

**Comment by AArnott** [comment]
I don't think we should modify DNOA to support this scenario as it is truly outside of the OpenID spec.
However, I think you can use an unmodified copy of DNOA to accomplish this simply by calling the `OpenIdRelyingParty.GetResponse` method overload that accepts an `HttpRequestBase` parameter where you can stick in your own instance that 'lies' about the incoming request URL, so that it looks like it came to the right one rather than your redirector.
