### ISSUE TITLE
Using ASP.Net AntiForgery in OAuth 2 Client instead Session

### ISSUE THREAD

**Issue by SLaks** [DotNetOpenAuth/DotNetOpenAuth#229]
I'm using OAuth 2 login, but I don't want to use ASP.Net session state.

DNOA uses the current session ID to mitigate CSRF attacks for OAuth 2 logins, so I need to replace that.

I'd like to replace it with ASP.Net's AntiForgery system, but doing so is somewhat difficult.

Can DNOA be modified to support this natively? (either by default or as an option)

**Comment by SLaks** [comment]
I did this using the following class:

``` csharp
///<summary>Uses ASP.Net's AntiForgery system to prevent CSRF attacks for OAuth logins.</summary>
///<remarks>This class prevents an attacker from initiating an OAuth login, logging in
///with his account, then sending the callback URL to a different user.
///
/// We put the AntiForgery system's FormToken in the OAuth state field.</remarks>
class AntiForgeryAuthorizationTracker : IClientAuthorizationTracker {
    readonly HttpContextBase context;
    public AntiForgeryAuthorizationTracker(HttpContextBase context) { this.context = context; }

    public void SetAuthorizationState(OutgoingWebResponse outgoingResponse) {
        var cookie = context.Request.Cookies[AntiForgeryConfig.CookieName];
        string oldCookieToken = cookie == null ? null : cookie.Value;
        string newCookieToken, formToken;
        AntiForgery.GetTokens(oldCookieToken, out newCookieToken, out formToken);

        // auth.Respond() will reset the response, so I must
        // append the cookie manually if it does not already
        // exist.
        if (newCookieToken != null)
            outgoingResponse.Headers.Add(HttpResponseHeader.SetCookie, AntiForgeryConfig.CookieName + "=" + newCookieToken + "; HttpOnly");
        outgoingResponse.Headers[HttpResponseHeader.Location] += "&state=" + Uri.EscapeDataString(formToken);
    }

    public IAuthorizationState GetAuthorizationState(Uri callbackUrl, string clientState) {
        if (context.Request.Cookies[AntiForgeryConfig.CookieName] == null)
            return null;
        AntiForgery.Validate(context.Request.Cookies[AntiForgeryConfig.CookieName].Value, clientState);
        return new AuthorizationState { Callback = callbackUrl };
    }
}
```

Before sending the `OutgoingWebResponse` for the initial authorization, you must call

```
new AntiForgeryAuthorizationTracker(HttpContext).SetAuthorizationState(outgoingResponse);
```

It would be great if this were integrated into the DNOA.  
(It would also be nice if `OutgoingWebResponse` supported cookies)

**Comment by AArnott** [comment]
`OutgoingWebResponse` has a headers collection, so yes, it supports cookies. Just set the appropriate header. If that doesn't work, please file a separate issue to track it.

**Comment by SLaks** [comment]
I was asking for a cookie API that didn't require me to build cookies by hand.  However, I realized later that `System.Net.Cookie` works fine for that; I can write

``` csharp
System.Net.Cookie cookie = ...;
outgoingResponse.Headers.Add(HttpResponseHeader.SetCookie, cookie.ToString());
```

**Comment by AArnott** [comment]
In your code snippet, what is this `AntiForgery` class you use? Just your own implementation or something that I don't immediately see in the .NET Framework but is there somewhere?

**Comment by SLaks** [comment]
It's in System.Web.WebPages.dll, which can be found on NuGet.

http://msdn.microsoft.com/en-us/library/system.web.helpers.antiforgery.aspx

**Comment by AArnott** [comment]
Hmmm... DNOA can't take a dependency on System.Web.WebPages. But no problem. The process of creating an anti-forgery token is simple enough. We can do it directly in DNOA.

**Comment by SLaks** [comment]
I ended up creating a separate class to abstract out the `AntiForgery` class:

``` csharp
///<summary>Holds the two halves of an ASP.Net AntiForgey protection token (to prevent CSRF attacks).</summary>
///<remarks>
/// ASP.Net creates one token for the cookie and a different token for the form, using
/// cryptography to ensure that only the web server can craft the correct form token.
/// (even if the attacker can read the cookie).
/// 
/// However, the built-in AntiForgery class is does not play well with DotNetOpenAuth,
/// since the OutgoingWebRequest class completely replaces the existing HttpResonse. I
/// wrote this class to bridge the two.  
/// 
/// If you aren't working with DotNetOpenAuth, you should use the standard AntiForgery
/// APIs directly instead.
/// </remarks>
public class AntiForgeryToken {
    private AntiForgeryToken() { }

    ///<summary>Gets a cookie to add to the current HTTP response, or null if the request already included an AntiForgery cookie (from a previous operation).</summary>
    public Cookie NewCookieToken { get; private set; }

    ///<summary>Gets a string to include with the form </summary>
    public string FormToken { get; private set; }

    ///<summary>Adds the new cookie token to an outing DotNetOpenAuth response, if applicable.</summary>
    public void SetCookie(OutgoingWebResponse outgoingResponse) {
        if (NewCookieToken == null)
            return;

        // Unlike System.Web.HttpCookie (ASP.Net server class),
        // System.Net.Cookie (client-side HTTP class) overrides
        // ToString() to return a value for the HTTP Set-Cookie
        // header.
        outgoingResponse.Headers.Add(HttpResponseHeader.SetCookie, NewCookieToken.ToString());
    }

    ///<summary>Checks the validity of a received form &amp; cookie token pair, throwing an HttpAntiForgeryException if they are missing or invalid.</summary>
    ///<param name="request">The HTTP request to read the cookie token from.</param>
    ///<param name="formToken">The incoming form token to validate.</param>
    public static void Validate(HttpRequestBase request, string formToken) {
        var cookie = request.Cookies[AntiForgeryConfig.CookieName];
        if (cookie == null)
            throw new HttpAntiForgeryException("The required anti-forgery cookie " + AntiForgeryConfig.CookieName + " is not present.");

        AntiForgery.Validate(cookie.Value, formToken);
    }

    ///<summary>Creates an AntiForgery token pair.</summary>
    ///<param name="request">The incoming HTTP request, which may contain an existing cookie token.</param>
    ///<returns>An object containing the form token to send to the client, along with a new cookie token if the request did not include one.</returns>
    public static AntiForgeryToken ForRequest(HttpRequestBase request) {
        var existingCookie = request.Cookies[AntiForgeryConfig.CookieName];
        string oldCookieToken = existingCookie == null ? null : existingCookie.Value;
        string newCookieToken, formToken;
        AntiForgery.GetTokens(oldCookieToken, out newCookieToken, out formToken);

        return new AntiForgeryToken {
            FormToken = formToken,
            NewCookieToken = CreateCookie(newCookieToken)
        };
    }
    static Cookie CreateCookie(string cookieToken) {
        if (cookieToken == null)
            return null;
        else    //TODO: Read <httpCookies> config
            return new Cookie(AntiForgeryConfig.CookieName, cookieToken) { HttpOnly = true, Secure = AntiForgeryConfig.RequireSsl };
    }
}
```

**Comment by SLaks** [comment]
For OAuth2, the AntiForgeryAuthorizationTracker class then becomes

``` csharp
///<summary>Uses ASP.Net's AntiForgery system to prevent CSRF attacks for OAuth logins.</summary>
///<remarks>This class prevents an attacker from initiating an OAuth login, logging in
///with his account, then sending the callback URL to a different user.
///
/// We put the AntiForgery system's FormToken in the OAuth state field.</remarks>
class AntiForgeryAuthorizationTracker : IClientAuthorizationTracker {
    readonly HttpContextBase context;
    public AntiForgeryAuthorizationTracker(HttpContextBase context) { this.context = context; }

    public void SetAuthorizationState(OutgoingWebResponse outgoingResponse) {
        var tokens = AntiForgeryToken.ForRequest(context.Request);
        tokens.SetCookie(outgoingResponse);
        outgoingResponse.Headers[HttpResponseHeader.Location] += "&state=" + Uri.EscapeDataString(tokens.FormToken);
    }

    public IAuthorizationState GetAuthorizationState(Uri callbackUrl, string clientState) {
        AntiForgeryToken.Validate(context.Request, clientState);

        return new AuthorizationState { Callback = callbackUrl };
    }
}
```

**Comment by SLaks** [comment]
This can also be used with OpenId like this:

#### When sending the redirect

``` csharp
var aft = AntiForgeryToken.ForRequest(Request);
var redirect = OpenIdClient.CreateRequest(...);

//This property creates a new instance every time
var response = redirect.RedirectingResponse;
aft.SetCookie(response);
return response.AsActionResult();
```

#### In the callback action

``` csharp
public string OpenIdCallback(string token) {
    AntiForgeryToken.Validate(Request, token);
    var result = OpenIdClient.GetResponse(Request);
```

**Comment by SLaks** [comment]
ASP.Net's AntiForgery system is more complicated than meets the eye.  (See my description in the `<remarks>` section of my `AntiForgeryToken` wrapper class)

Using the `AntiForgery` class directly allows the cookie to be reused for both OpenID logins and regular form POSTs.

Perhaps this should be an extension point (like `IClientAuthorizationTracker`, but also able to modify redirecting requests)?  
You can then make a separate assembly & NuGet package that depends on System.Web.WebPages.

**Comment by AArnott** [comment]
Yes, the abstraction will help if we have to use the WebPages `AntiForgery` class. However, the complexity in that class is largely due to handling users that are already logged in. And in OpenID at least that's not an issue. For OAuth 2 that can potentially be an issue, I'm not sure. I need to research it more.

**Comment by AArnott** [comment]
The Microsoft ASP.NET team has already written [an XSRF token generator that has no WebPages dependency](https://github.com/DotNetOpenAuth/DotNetOpenAuth/blob/master/src/DotNetOpenAuth.AspNet/OpenAuthSecurityManager.cs#L146) that's part of DotNetOpenAuth.AspNet. We can probably promote this code to DotNetOpenAuth.Messaging so that others within DNOA can use it.

**Comment by AArnott** [comment]
Beware of your use of `Cookie.ToString()`. Apparently it disregards _most_ of its data, including the `Secure` property you set in your above snippet.

**Comment by rcollette** [comment]
@AArnott - Can you comment on whether this change addresses holes in open id unsolicited assertions automatically?  If not, I read your email discussion regarding the RP setting cookie values and soliciting the user for intent but the specific process of setting/checking a cookie value is not clear to me nor am I clear on what I would do to solicit intent from a user or when exactly I would do that.   I am using unsolicited assertions in a production environment so it is an important topic for me.

**Comment by AArnott** [comment]
John Bradley would probably be most qualified to answer your question. I
believe his answer would be 'yes', but the exact reasons why I don't
recall. Plus, as is often the case, when it comes to cookies and XSRF, much
of the responsibility inevitably lies with the web app itself rather than
the protocol or a library, so you'd probably have to thoroughly understand
the issues and correctly apply the mitigation yourself rather than just
switch to another protocol for immunity.

IIRC, the unsolicited assertion attack vector is that if an evil web site
can send one to an RP that you later visit (via a hidden iframe, perhaps),
you may think you're logged in as you but actually be logged in as the
attacker. Then the attacker may be able to gain access to those things you
do while logged in with the wrong account.

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre
