### ISSUE TITLE
Authenticated request to LinkedIn API is not working

### ISSUE THREAD

**Issue by ghost** [DotNetOpenAuth/DotNetOpenAuth#232]
I'm using the LinkedInClient class in DNOA.AspNet.dll to make an authenticated request to LinkedIn API. 

The authentication is successful, but when making query to the profile API, it fails. Upon debugging, I found out that the signature that DNOA Core produces is different from the accepted signature from the LinkedIn OAuth Test Console (https://developer.linkedin.com/oauth-test-console)

Here is the data that goes into the test console:

```
API Key: ub78frzrn0yf
Secret key: ExJXsYl7Or8OfK98
Member token: 852863fd-05da-4d80-a93d-50f64f966de4
Member secret: b197333b-470a-43b3-bcd7-49d6d2229c4c
HTTP verb: GET
URL: https://api.linkedin.com/v1/people/~:(id,first-name,last-name,headline,industry,summary)
Query parameters:
Nonce: ugEB4bst
Timestamp: 1353545248
OAuth version: 1.0
```

This generates the following signature base string:

GET&https%3A%2F%2Fapi.linkedin.com%2Fv1%2Fpeople%2F~%3A%28id%2Cfirst-name%2Clast-name%2Cheadline%2Cindustry%2Csummary%29&oauth_consumer_key%3Dub78frzrn0yf%26oauth_nonce%3DugEB4bst%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1353545248%26oauth_token%3D852863fd-05da-4d80-a93d-50f64f966de4%26oauth_version%3D1.0

DNOA produces this signature: fiGCdbmMhTOrA/dkZC4JcRuAF8Q=

The Test console produces a different one: l09yeD9cr4+h1eoUF4WBoGEHrlk=

**Comment by AArnott** [comment]
Well at first glance there is plenty of weirdness in the URL. There is a colon in the path, which I've never seen before, and I don't think the escaping is quite right.

**Comment by AArnott** [comment]
When I put all this data into DNOA, I got the same signature that LinkedIn produces. 
I'm digging a little deeper to see if I can figure out how you came up with the fiGCdbmMhTOrA/dkZC4JcRuAF8Q= signature, Luan.

**Comment by ghost** [comment]
I used the LinkedInClient class and pass in the API key and API secret in the constructor, and went through the authentication process.

I then put a break point in the class that produces the signature (I forgot its name.)

**Comment by AArnott** [comment]
Luan, I've added an interop test that uses the values you provided in this bug and demonstrates that DNOA generates the same signature as the LinkedIn test console. Can you investigate further to find out where the bug really is?

**Comment by ghost** [comment]
Where’s your interop test? on which branch?

Sent from Windows Mail

From: Andrew Arnott
Sent: ‎November‎ ‎22‎, ‎2012 ‎9‎:‎00‎ ‎PM
To: DotNetOpenAuth/DotNetOpenAuth
CC: Luan Nguyen
Subject: Re: [DotNetOpenAuth] Authenticated request to LinkedIn API is not working (#232)

Luan, I've added an interop test that uses the values you provided in this bug and demonstrates that DNOA generates the same signature as the LinkedIn test console. Can you investigate further to find out where the bug really is?

**Comment by AArnott** [comment]
master branch of the https://github.com/AArnott/dotnetopenid repo

**Comment by ghost** [comment]
Sorry for the delay. I’m testing it now.

**Comment by ghost** [comment]
I have found the root cause of the issue. The LinkedIn client uses the AuthenticationOnlyCookieOAuthTokenManager class to manage the token and this class doesn't handle replacing requestToken with accessToken correctly. I'll send out a pull request later with this fix. I'll go ahead and close the issue. Thanks for your help.
