### ISSUE TITLE
Unable to remove DotNetOpenAuth OAuth 2.0 core draft 4 from Office App

### ISSUE THREAD

**Issue by tofutim** [DotNetOpenAuth/DotNetOpenAuth#234]
I have an Office app (2013) that somehow got tagged with the OAuth 2.0 Core nuget in the nuget manager, however, I'm unable to remove it.

**Comment by AArnott** [comment]
That doesn't sound like a DotNetOpenAuth bug. Please file it (with more detail) with the [NuGet project](http://nuget.codeplex.com/workitem/list/basic).
