### ISSUE TITLE
LinkedIn client does not appear to work

### ISSUE THREAD

**Issue by tofutim** [DotNetOpenAuth/DotNetOpenAuth#237]
I'm able to login, but when it redirects back to my site it fails. I think the problem happens somehow near base.WebWorker.PrepareAuthorizedRequest(profileEndpoint, accessToken)

**Comment by tofutim** [comment]
Looks like some solutions are found here - https://github.com/DotNetOpenAuth/DotNetOpenAuth/issues/175 - has this been addressed with a pull request yet?

**Comment by AArnott** [comment]
Duplicate of #232
