### ISSUE TITLE
ResourceServer.GetPrincipal() throws other exceptions than ProtocolFaultResponseException

### ISSUE THREAD

**Issue by liwp** [DotNetOpenAuth/DotNetOpenAuth#238]
According to the resourceServer.GetPrincipal() documentation a ProtocolFaultResponseException should be thrown if the client is not authorized. I've now managed to get the method to throw two other exceptions.

By accidentally passing the refresh token in the Http request instead of the access token I managed to get the GetPrincipal() call to throw a FormatException (Because the refresh token is not a valid Base64 string).

And by passing in rubbish ("foo") as the access token in the Http request resulted in an EndOfStreamException from DotNetOpenAuth.Messaging.MessagingUtilities.ReadBuffer().

**Comment by AArnott** [comment]
Thanks for this report. We've fixed a variety of such exceptions for the v4.1.4 release. Please upgrade when it's available (very soon) and reactivate if it still repros for you.
