### ISSUE TITLE
INFO logging in the Resource Owner Credentials Flow prints out user credentials

### ISSUE THREAD

**Issue by liwp** [DotNetOpenAuth/DotNetOpenAuth#243]
When calling WebServerClient.ExchangeUserCredentialForToken() method, DotNetOpenAuth prints out the following logging:

INFO  Messaging.Channel - Prepared outgoing AccessTokenResourceOwnerPasswordCredentialsRequest (2.0) message for http://localhost:42084/OAuth/Token:
        username: username@example.com
        password: S3cret
        scope: my_scope
        grant_type: password

I feel that this logging should either be at DEBUG level so that the app can be run with log level INFO without exposing user credentials, or the credentials should be masked.

At the moment it's quite likely that the user's credentials will be accidentally exposed on the console, or even worse, written to some log file somewhere on the system.

There's other logging that happens during the Resource Owner Credentials Flow (and presumably during all the OAuth2 flows) that should also probably be at DEBUG level rather than INFO or WARN levels. E.g.

WARN  DotNetOpenAuth.Messaging - Multiple message types seemed to fit the incoming data: {AccessTokenSuccessResponse (2.0),
}nauthorizedResponse (2.0),

INFO  Messaging.Channel - Processing incoming AccessTokenSuccessResponse (2.0) message: ...

At the moment I've configured DotNetOpenAuth log level to ERROR to avoid unnecessary chatter from DotNetOpenAuth during normal operation.

**Comment by AArnott** [comment]
Good feedback. Thanks.
