### ISSUE TITLE
Exception logging when the authorization server Token endpoint returns a 404

### ISSUE THREAD

**Issue by liwp** [DotNetOpenAuth/DotNetOpenAuth#244]
If the /OAuth/Token endpoint returns a 404 error, the DotNetOpenAuth logs the WebException, which results in a dump of the response content.

The web server that is hosting our authorization server has custom error pages configured, so we get  ~150 lines of HTML in our DotNetOpenAuth logs.

What we'd really like is just the return code from the HTTP response, and possibly the one line message.

**Comment by AArnott** [comment]
Can you just turn down logging verbosity for that particular logger? Many people find the full response content immensely valuable.

**Comment by liwp** [comment]
Yes, I can, but the exception is logged at ERROR level, so I have to set the DotNetOpenAuth.Http log level to FATAL, and now I worry that I'm missing other ERROR messages.

**Comment by AArnott** [comment]
Ah, that makes sense then. I think we can do something to fix that.
