### ISSUE TITLE
The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by ulfathussain** [DotNetOpenAuth/DotNetOpenAuth#259]
Hi 

I have searched for the integration of twitter. I had done it using dotnetopenauth but I had skipped the steps of twiiter sign in from the sample.
# I used this function for starting sign in process

[code]
VMLServiceProviderDescription spd = new VMLServiceProviderDescription();
            var serviceProvider = spd.GetServiceDescription(VMLServiceProviderDescription.VMlServiceProviderName.Twitter);
            var consumer = new WebConsumer(serviceProvider, _tokenManager);

```
        // Url to redirect to
        var authUrl = new Uri(Request.Url.Scheme + "://" + Request.Url.Authority + "/Home/OAuthCallBack");


        // request access
        var redirectParameters = new Dictionary<string, string>();
        redirectParameters["force_login"] = "true";
        consumer.Channel.Send(consumer.PrepareRequestUserAuthorization(authUrl, null, redirectParameters));

        // This will not get hit!
        return null;
```
# [/code]

Then used this code for callback

======>
VMLServiceProviderDescription spd = new VMLServiceProviderDescription();
            var serviceProvider = spd.GetServiceDescription(VMLServiceProviderDescription.VMlServiceProviderName.Twitter);
            var consumer = new WebConsumer(serviceProvider, ApplicationLevelData.GetInMemoryTokenManager());
            var accessTokenResponse = consumer.ProcessUserAuthorization();

```
        // If we didn't have an access token response, this wasn't called by the service provider
        if (accessTokenResponse == null)
            return RedirectToAction("Index");

        // Extract the access token
        string screenname = accessTokenResponse.ExtraData["screen_name"].ToString();
        ViewData["ScreenName"] = "Screen Name = " + screenname;

        string user_id = accessTokenResponse.ExtraData["user_id"].ToString();
         return View();
```
# 

The problem in above was that whenever the authentcation started, then if user was logged in on twitter, then the code auto-authorized the user with user involvement(in the process). I wondered that "force_login" was not working as required. If there is problem in the above code then please let me know so that I can fix it using above code .
# Else , I looked for samples and implemented in another way discussed below.

Then I looked the sample of Dotnetopenauth which were using a page for twitter sign in and one for displaying the details.
The page in code load was
# 

 if ((Request["openid_identifier"] == "http://twitter.com/") || ((Request["oauth_token"] != null) && (Request["oauth_token"].Length > 1)))
            {
                if (TwitterConsumer.IsTwitterConsumerConfigured)
                {
                    string screenName;
                    int userId;
                    if (TwitterConsumer.TryFinishSignInWithTwitter(out screenName, out userId))
                    {
                        //userId is now a unique numeric id for the user
                        //screenName is now their Twitter username

```
                    //use these values to do whatever you want
                }
            }
        }
        else
        {
            TwitterConsumer.StartSignInWithTwitter(true).Send();
        }
```
# 

and when "TwitterConsumer.StartSignInWithTwitter(true).Send();" is executed, the error is displayed. 

Please note that I have added the following classes of Dotnetapplicationblock in my 
application.
1)- TwitterConsumer.cs
2)- InMemoryTokenManager.cs

i have set the apikey and secret correctly. Am I missing some thing.

Regards
Ulfat Hussain

**Comment by kubilay902** [comment]
its an https issue, I dont know who is going to fix it but you should change it manually from the source :( I couldn't find any other way

**Comment by khajoo** [comment]
In my case it was resolved by setting the callback url in the application setting!
