### ISSUE TITLE
Problem with ClaimsResponse, if users's language + country doesn't make a valid culture

### ISSUE THREAD

**Issue by AkosLukacs** [DotNetOpenAuth/DotNetOpenAuth#260]
Tried to authenticate with google, and got this exception:
`Culture is not supported. Parameter name: name en-HU is an invalid culture identifier`. 
Stacktrace: 
`System.Globalization.CultureNotFoundException: Culture is not supported. Parameter name: name en-HU is an invalid culture identifier. at System.Globalization.CultureInfo.GetCultureInfo(String name) at DotNetOpenAuth.OpenId.Extensions.SimpleRegistration.ClaimsResponse.get_Culture()`

The exceptions (and the as well [source](https://github.com/DotNetOpenAuth/DotNetOpenAuth/blob/master/src/DotNetOpenAuth.OpenId/OpenId/Extensions/SimpleRegistration/ClaimsResponse.cs#L198) ) tell that you are trying to concatenate language + country.

I think it's possible that someone is living in a foreign country changes the country to the place where (s)he actually lives, but leaves the original language. That could create all kinds of illegal language-country combinations.

**Comment by AArnott** [comment]
Thanks for the pull request. Closing this issue as it is duplicate now.
