### ISSUE TITLE
The Protocol of OAuth 2.0

### ISSUE THREAD

**Issue by aqbjteddy** [DotNetOpenAuth/DotNetOpenAuth#275]
Hi, I got a question.
Is https protocol necessary to OAuth 2.0 server ?

<pre>
client.RequestUserAuthorization();
</pre>

<pre>
This message can only be sent over HTTPS.
</pre>

**Comment by aqbjteddy** [comment]
ahh, I found settings in web.config file.

``` xml
    <!-- Relaxing SSL requirements is useful for simple samples, but NOT a good idea in production. -->
    <messaging relaxSslRequirements="true"/>
```

**Comment by phw** [comment]
I just wanted to note that you really should use SSL for production. The design of OAuth 2 requires SSL for secure token exchange. OAuth 1 didn't require SSL but used a more complex token exchange algorithm.
