### ISSUE TITLE
Please update nuget package

### ISSUE THREAD

**Issue by aqbjteddy** [DotNetOpenAuth/DotNetOpenAuth#276]
I just found some differences of classes between github & nuget, and it is very confused for me until check source code on github.

thanks,
teddy

**Comment by AArnott** [comment]
The latest release on NuGet is v4.3. And GitHub agrees with it virtually exactly. You just have to be looking at [the right branch](1).

**Comment by aqbjteddy** [comment]
I just downloaded full code from github, and found classes are different.You can take a look at class StandardAccessTokenAnalyzer.

**Comment by aqbjteddy** [comment]
v5.0 ?

**Comment by AArnott** [comment]
Evidently you downloaded the source code for the wrong branch. v5.0 is in the master branch. The last released version is v4.3, so if you want matching sources you need to download the source code for the tag for that version.
Please refer to github documentation for how to do this.

**Comment by aqbjteddy** [comment]
Ok, thank u.

------------------ 原始邮件 ------------------
发件人: "Andrew Arnott"; 
发送时间: 2013年5月10日(星期五) 中午12:49
收件人: "DotNetOpenAuth/DotNetOpenAuth"; 
抄送: "aqbjteddy"522133684@qq.com; 
主题: Re: [DotNetOpenAuth] Please update nuget package (#276)

Evidently you downloaded the source code for the wrong branch. v5.0 is in the master branch. The last released version is v4.3, so if you want matching sources you need to download the source code for the tag for that version.
 Please refer to github documentation for how to do this.

&mdash;
