### ISSUE TITLE
Many samples missing .nuget/nuget.targets

### ISSUE THREAD

**Issue by eleven41** [DotNetOpenAuth/DotNetOpenAuth#277]
- OAuth2ProtectedWebApi
- OAuthAuthorizationServer
- OAuthConsumer
- OAuthServiceProvider

Opening the samples solution complains and blocks loading of the projects.

**Comment by eleven41** [comment]
Found that if you load the main solution, these projects will find the solution's nuget information.

**Comment by vijayantkatyal** [comment]
copy .nuget folder from src to samples, it will work
