### ISSUE TITLE
Why the field "UserName" of IAccessTokenRequest is null ?

### ISSUE THREAD

**Issue by aqbjteddy** [DotNetOpenAuth/DotNetOpenAuth#278]
hi, @AArnott 

``` csharp
public ActionResult AuthorizeResponse(bool isApproved)
{
    ...
    response = this._authorizationServer.PrepareApproveAuthorizationRequest(pendingRequest,"username");
    ...
}
public AccessTokenResult CreateAccessToken(IAccessTokenRequest request)
{
    ...
    accessToken.User = request.UserName; // request.UserName is null, it should not be "username"?
    accessToken.ExtraData["ticket"] = "test";
    return new AccessTokenResult(accessToken);
}


// web api
var token = resourceServer.GetAccessToken(); //  token.ExtraData has value, but token.User is null.

```

thank you.

**Comment by aqbjteddy** [comment]
I should add that I did not use openid provider but forms authentication instead.

**Comment by aqbjteddy** [comment]
Authenticate server and web api is independent, the logged user get access token from authenticate server via third client server firstly, then request web api with token, so i need both clientid and userid included in token.

Only the logged user can access to web api.

It can be realized by sharing cookie between authenticate server and web api, but if I want set userid to token extra data, how to do?

**Comment by AArnott** [comment]
At first glance, you appear to be doing everything right. But please take questions to the dotnetopenid@googlegroups.com mailing list.

**Comment by aqbjteddy** [comment]
@AArnott 
It seems that I need an openid provider.

**Comment by AArnott** [comment]
OpenId and Oauth are orthogonal. You don't need one for any features in the other.

**Comment by aqbjteddy** [comment]
If I want to call web api at server side, I must konw the current user logged in, cookie for logging is stored at browser.

I call web api via javascript though cors at present.

**Comment by AArnott** [comment]
When calling a WebAPI, no one is "logged in" at the service at all. A client makes the call, with an authorization header bearing some kind of token that shows the client has the authority to make such a call. That token often refers to the user who authorized it, which a typical setup is the same user as the one whose data the client will then be accessing.
But the manner by which the user authorized that token (including logging in to do so) is still orthogonal. It could have been username+password, OpenID, smartcard, anything.

**Comment by aqbjteddy** [comment]
But user info is not included in the token, how to get user info from token?

**Comment by AArnott** [comment]
Check out the `GetAccessToken` and `GetPrincipal` methods on the [ResourceServer](http://docs.dotnetopenauth.net/v4.2/html/AllMembers_T_DotNetOpenAuth_OAuth2_ResourceServer.htm) class.

**Comment by aqbjteddy** [comment]
![token_user_id](https://f.cloud.github.com/assets/1908124/516104/d2d38376-be99-11e2-8839-29abe50b332d.png)

Please take a look at the pic above. OAuthPrincipal only includes the client id.

**Comment by AArnott** [comment]
That means the authorization server didn't encode the authorizing username in the access token. Please review that code on your side.

**Comment by AArnott** [comment]
...and this is open source, so please review the code in DNOA as necessary (you can use http://www.symbolsource.org/Public to help you step through the DNOA-compiled assembly with source and symbols). I've far expended my time on this particular request. sorry I can't offer more (for free).

**Comment by aqbjteddy** [comment]
Firstly thank you for your attention to this request, and I supposed that the code is reliable, so I was always trying to find the trouble in my project.

Anyway, DNOA is very powful, and I will debug it with source code.
