### ISSUE TITLE
The Version 4.2.0.0 is not compatible with the Version 4.0.0.12075

### ISSUE THREAD

**Issue by zxhlelva** [DotNetOpenAuth/DotNetOpenAuth#279]
Some months ago , I use the Version  4.0.0.12075 to build my first oauth server.
Its Url is like OauthWebSite1/Oauth.
And my web service use Oauth to do the authentication.
My webService's server's url is like WebService1/API

Now, I would like to upgrade my oauth server with the Version 4.2.0.0.
Its Url is like OauthWebSite2/Oauth.

But I want OauthWebSite1/Oauth can still work since I have a number of clients who still access to this url.
Unfortunately when I upgrade WebService1/API with the new dll of Version 4.2.0.0(my web service site calls GetPrincipal to verify the user, it is why I need to upgrade this site as well).I found that my web service site can't recognize the token generated by OauthWebSite1/Oauth.

Would you please kindly give some advice?

Thanks

**Comment by AArnott** [comment]
Q&A such as this is best suited for our mailing list: dotnetopenid@googlegroups.com
If you do post there, please indicate whether you're using OAuth 1 or 2.
