### ISSUE TITLE
FacebookClient can't be customized

### ISSUE THREAD

**Issue by pedropaf** [DotNetOpenAuth/DotNetOpenAuth#284]
I am working on an MVC app, and I am using facebook connect, using the class provided FacebookClient, which is a sealed class. I need to get the user email, so I need to set a scope in the request URS to facebook, also the function GetUserData() has to be overriden. 

I thought, I can inherit FacebookClient and I'll customize it. This can't be done because FacebookClient is sealed. Maybe adding the scope to the class and customize GetUserData using a lambda function could be a solution. Any ideas? 

For the time being I've just copied FacebookClient into a new class and customized it.

Thanks,

**Comment by AArnott** [comment]
This has already been fixed by 7af5e055d9b92629344a87886a097e0c99fe5f5e
