### ISSUE TITLE
RijndaelManaged not FIPS compatible

### ISSUE THREAD

**Issue by dustinmoris** [DotNetOpenAuth/DotNetOpenAuth#285]
Hi,

we are implementing DotNetOpenAuth into a new project and
DotNetOpenAuth.Messaging.MessagingUtilities.CreateSymmetricAlgorithm
uses hard coded the
System.Security.Cryptography.RijndaelManaged
which is not FIPS compatible.

Typical FIPS error:
[InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.]
   System.Security.Cryptography.RijndaelManaged..ctor() +9702832
...

You should be using Aes instead (see: http://csrc.nist.gov/publications/fips/fips197/fips-197.pdf).

I came across an older thread and I applied all the other mappings in my config file, but this one can't be mapped.

Any chances of having this fixed in the near future as well?

**Comment by AArnott** [comment]
Good catch. I think replacing this with `SymmetricAlgorithm.Create()` should fix the problem (since you can then dictate the type in the .config file) right?

**Comment by dustinmoris** [comment]
Yes, that is correct.

I just had a look through the whole solution and you use the RijndaelManaged more than once in MessagingUtilities but nowhere else from what I can see.

I tried to replace it with Aes.Create() and it build fine, didn't have a chance yet to try if this makes the whole project FIPS compatible though (but I hope so :)).

Using SymmetricAlgorithm.Create() should be as good as Aes.Create(). I can map it then in the config!

(BTW, thank you for your really quick response!)

**Comment by dustinmoris** [comment]
Sweet, thank you!

**Comment by dustinmoris** [comment]
Do you know when we can roughly expect the release of 4.3.1?

**Comment by AArnott** [comment]
By end of this week.

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by tmiller71** [comment]
Digging up an old thread.  I can't get this to work if FIPS is enabled.  I've tried https://github.com/DotNetOpenAuth/DotNetOpenAuth/issues/47 and still no luck.  Any input woudl be greatly appreciated.
