### ISSUE TITLE
CreateFormatter unexpected validation

### ISSUE THREAD

**Issue by crixo** [DotNetOpenAuth/DotNetOpenAuth#298]
DotNetOpenAuth.OAuth2\OAuth2\AccessToken.cs -> 
CreateFormatter(RSACryptoServiceProvider signingKey, RSACryptoServiceProvider encryptingKey)

Requires.That(signingKey == null || !signingKey.PublicOnly, "signingKey", "requires private key");

works fine within AuthorizationServer sample, but it throws within ResourceServer sample... as far as I understood, signingKey parameter has to be PublicOnly within ResourceServer

**Comment by panterlo** [comment]
Take a look what what I wrote in https://github.com/DotNetOpenAuth/DotNetOpenAuth/issues/308. Basically this just seems like a coding error. The signingKey should not be null, but in the evaluation is must be null.

**Comment by AArnott** [comment]
Agreed. This entire line should probably be removed. And the appropriate null-or-private-key check added to the Serialize method.
