### ISSUE TITLE
Sources for DotNetOpenAuth.AspNet

### ISSUE THREAD

**Issue by awaegel** [DotNetOpenAuth/DotNetOpenAuth#299]
Are sources available for the AspNet extensions? I'd like to modify them to add to the extraData. I understand the nuget package is produced by Microsoft, but I think it's the same author?

**Comment by DavidChristiansen** [comment]
Does this help ? http://www.symbolsource.org/Public/Metadata/NuGet/Project/DotNetOpenAuth.AspNet
