### ISSUE TITLE
nuget build of latest version has a failed dependency

### ISSUE THREAD

**Issue by AartBluestoke** [DotNetOpenAuth/DotNetOpenAuth#309]
> nuget install dotnetopenauth -Version 4.3.2.13293
> Attempting to resolve dependency 'DotNetOpenAuth.OpenId.RelyingParty.UI (= 4.3.2
> .13293)'.
> Attempting to resolve dependency 'DotNetOpenAuth.OpenId.Core.UI (= 4.3.2.13293)'
> .
> Attempting to resolve dependency 'DotNetOpenAuth.Core.UI (= 4.3.2.13293)'.
> Attempting to resolve dependency 'DotNetOpenAuth.Core (= 4.3.2.13293)'.
> Attempting to resolve dependency 'CodeContracts.Unofficial'.
> Attempting to resolve dependency 'Microsoft.Net.Http'.
> Attempting to resolve dependency 'Microsoft.Bcl (= 1.1.3)'.
> Attempting to resolve dependency 'Microsoft.Bcl.Build (= 1.0.4)'.
> Attempting to resolve dependency 'DotNetOpenAuth.Mvc (= 4.3.2.13293)'.
> Unable to resolve dependency 'DotNetOpenAuth.Mvc (= 4.3.2.13293)'.

I'm not sure if this is the correct place to report this, but there isn't an issues over with the nuget package at http://www.nuget.org/packages/DotNetOpenAuth/

edit:
also reported at http://stackoverflow.com/questions/19502300/dotnetopenauth-nuget-package-installation-failed (not by me)

**Comment by AArnott** [comment]
I don't understand why the log shows that DotNetOpenAuth.Mvc is a dependency. It is not.
DotNetOpenAuth v4.3.2 doesn't include the MVC 5 package at all. And if you want it, you can install the DotNetOpenAuth.Mvc5 package (note the 5 at the end). The DotNetOpenAuth.Mvc package is only for DNOA v5.

**Comment by AArnott** [comment]
Ah, I see the DotNetOpenAuth.OpenId.RelyingParty.UI package has an accidental dependency on it.

**Comment by AArnott** [comment]
Fixed by faa3fd57f64272bbe80cd72f6945e5d311d075fb

**Comment by ghost** [comment]
How do I get off the email list here. Driving me nuts! ;)

**Comment by AArnott** [comment]
@mwebsolutions Try un-following the issue on github. 
Ultimately how you follow/unfollow issues isn't a project-related issue, it's between you and github. I suggest you check their documentation or forums.

**Comment by ghost** [comment]
Thanks so much – bit of a head explosion! ;)
