### ISSUE TITLE
Implement OpenID provider

### ISSUE THREAD

**Issue by lorddev** [DotNetOpenAuth/DotNetOpenAuth#314]
There appear to be no examples in the wiki on how to roll your own SSO provider for internal apps.

**Comment by DavidChristiansen** [comment]
Please look at https://github.com/DotNetOpenAuth/DotNetOpenAuth.Samples for examples of implementation

**Comment by lorddev** [comment]
Wow you're a big help... Not.

Once I figure it out after slaving over the demos for hours I'll write up some documentation and add it to the wiki to make it easier for the next guy.

—

**Comment by DavidChristiansen** [comment]
I would hope reviewing the given sample OpenID Provider (MVC or WebForms) would not involve any slaving over - however if you do find challenges then please do let me know and work on resolving them, documenting our findings as appropriate.

https://github.com/DotNetOpenAuth/DotNetOpenAuth.Samples/tree/master/src/OpenID/OpenIdProviderMvc
