### ISSUE TITLE
AccessToken CreateFormatter incorrect precondition on signingKey parameter

### ISSUE THREAD

**Issue by michael2m** [DotNetOpenAuth/DotNetOpenAuth#318]
AccessToken.CreateFormatter(RSACryptoServiceProvider signingKey, RSACryptoServiceProvider encryptingKey)

has the following precondition:
    Requires.That(signingKey == null || !signingKey.PublicOnly, ...

The condition is incorrect. This issue prevents checking signatures with a public key (e.g. by resource server).

**Comment by AArnott** [comment]
Duplicate of #298
