### ISSUE TITLE
Can DotNetOpenAuth be used in .net framework 1.1 ?

### ISSUE THREAD

**Issue by GodIT** [DotNetOpenAuth/DotNetOpenAuth#319]
My environment is VS2003 and framework is 1.1,How  Can I get the dll  for framework 1.1 or where go get ?

**Comment by AArnott** [comment]
DotNetOpenAuth does not work on the .net framework 1.1.

**Comment by AArnott** [comment]
and if I may advise, you should not be using that version of the.net framework either for anything having to do with security. It's full of security holes that are only fixed in newer versions
