### ISSUE TITLE
Serviceprovider expects timestamp in milliseconds

### ISSUE THREAD

**Issue by karstenols** [DotNetOpenAuth/DotNetOpenAuth#322]
Im currently trying to use the DotNetOpenAuth 1.0 consumer to integrate with a serviceprovider which requires timestamps to be in milliseconds. 

Unfortunately the OAuth1HttpMessageHandlerBase does not easily allow for developers to extend and provide an alternative timestamp mechanism. (Because the ToTimeStamp in the OAuth1HttpMessageHandlerBase method is marked privat and consequently cannot be overriden in derived classes). 

A solution could maybe be to allow developers to provide their own timestamp routine. I have made a small modification to accommodate this problem (pull request #321)

**Comment by karstenols** [comment]
Is it only me that find this issue problematic? I hope my pull request #321 can be accepted.

**Comment by AArnott** [comment]
[OAuth 1.0 requires that the parameter be seconds](http://tools.ietf.org/html/rfc5849#section-3.3). It sounds like the server you're calling that expects milliseconds is either not OAuth 1.0 or has a bug in it. DotNetOpenAuth implements the spec and as a general library we avoid flexibility to accommodate bugs in other implementations, but rather encourage you to push for those bugs to be fixed.
