### ISSUE TITLE
Unable run sample of OAuthClient

### ISSUE THREAD

**Issue by tangzhen** [DotNetOpenAuth/DotNetOpenAuth#332]
After compile all source code of project, and I get the error below when I use OAuthClient login in with facebook:
I don't know it is the issue or which config I'm incorrect.
I running with VS2013 and chrome.
## Error

Attempt by method 'DotNetOpenAuth.OAuth2.WebServerClient+<PrepareRequestUserAuthorizationAsync>d__3.MoveNext()' to access method 'System.Collections.Generic.List`1<System.__Canon>..ctor()' failed.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.MethodAccessException: Attempt by method 'DotNetOpenAuth.OAuth2.WebServerClient+<PrepareRequestUserAuthorizationAsync>d__3.MoveNext()' to access method 'System.Collections.Generic.List`1<System.__Canon>..ctor()' failed.

Source Error: 

```
Line 106:           // verifiable for the same user/session.
Line 107:           // If the host is implementing the authorization tracker though, they're handling this protection themselves.
Line 108:           var cookies = new List<CookieHeaderValue>();
Line 109:           if (this.AuthorizationTracker == null) {
Line 110:               string xsrfKey = MessagingUtilities.GetNonCryptoRandomDataAsBase64(16, useWeb64: true);
```

Source File: c:\workspace\demo\DotNetOpenAuth\src\DotNetOpenAuth.OAuth2.Client\OAuth2\WebServerClient.cs    Line: 108 

Stack Trace: 

```
[MethodAccessException: Attempt by method 'DotNetOpenAuth.OAuth2.WebServerClient+<PrepareRequestUserAuthorizationAsync>d__3.MoveNext()' to access method 'System.Collections.Generic.List`1<System.__Canon>..ctor()' failed.]
   DotNetOpenAuth.OAuth2.<PrepareRequestUserAuthorizationAsync>d__3.MoveNext() in c:\workspace\demo\DotNetOpenAuth\src\DotNetOpenAuth.OAuth2.Client\OAuth2\WebServerClient.cs:108
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   OAuthClient.<<Page_Load>b__0>d__1.MoveNext() in c:\workspace\demo\DotNetOpenAuth\samples\OAuthClient\Facebook.aspx.cs:28
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Web.UI.<ExecuteTasksAsync>d__0.MoveNext() +507
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Web.UI.<ProcessRequestAsync>d__2c.MoveNext() +1145
```

**Comment by ghost** [comment]
I'm also having the same problem.   Downloaded the source, compiled.  Ran the OAuth projects in the browser, and got the same eror.

I'm on Windows 7 as a non-admin user, running Visual Studio 2013 as administrator.

**Comment by mberubenet** [comment]
Same error on my side.

I run window 7 (as admin) and VS2013 as admin also.

**Comment by IakovK** [comment]
I have the same problem.
I'm on Windows 7 as a non-admin user, running Visual Studio 2013 as administrator.

**Comment by rcollette** [comment]
+1

**Comment by rcollette** [comment]
The problem is that the DotNetOpenAuth.OAuth2.Client project references System.Net.Http.Formatting version 5.0 which is part of the WebApi package.   I changed the reference to System.Net.Http.Formatting version 4.0 which is included in the .NET 4.0/4.5 BCL and the issue was resolved.   I don't know how that impacts other code/tests at the moment.  The only place that CookieHeaderValue is used is in this method.

I'm not sure the client library should have any dependencies on Web Api.   My preference is that frameworks parallel the Microsoft assemblies to the extent possible  such that we don't create these types of dependencies.   My assumption is that this assembly reference was accidentally introduced at some point.

**Comment by IakovK** [comment]
Thanks! I changed the reference my copy and it works.

**Comment by JohannesRudolph** [comment]
Sorry guys, I can hardly consider this a fix... It's a workaround at best. I'm not sure what the consequenes of sticking with System.Net.Http.Formatting are for a project that's using Web Api 2.2. 

Ideally, DNOA should not have a dependency on System.Net.Http.Formatting OR it should properly state which version it supports in its NuGet package.
