### ISSUE TITLE
Deadlock when using System.Net.Http > 2.1.0.0 

### ISSUE THREAD

**Issue by jdevillard** [DotNetOpenAuth/DotNetOpenAuth#333]
I'm facing an issue when I'm trying to test the sample of Client OAuth with last DLL of System.Net.Http and System.Net.Http.WebRequest.

If I use the version 4.0.0.0, the code works fine, but if I use the version 2.1.0.0 or later, the call is blocked on the line : 

``` csharp
var body = client.GetStringAsync(new Uri(resourceServerUri, Paths.MePath)).Result;
```

I don't know where the problem is but I've seen that if I change the 

``` csharp
_webServerClient.CreateAuthorizingHandler(_accessToken)
,
```

 with my own implementation the code is not blocked.

This issues forced me to redevelop the handler because I've to use the latest dll of System.Net for other components of my program.

I've also tested with the pre-version 5.0.0.0 and the bug is still here.

Here is the code of the sample I've used.

``` csharp
class Program
{
    private static WebServerClient _webServerClient;
    private static string _accessToken;

    static void Main(string[] args)
    {
        InitializeWebServerClient();

        Console.WriteLine("Requesting Token...");
        RequestToken();

        Console.WriteLine("Access Token: {0}", _accessToken);

        Console.WriteLine("Access Protected Resource");
        AccessProtectedResource();            
    }

    private static void InitializeWebServerClient()
    {
        var authorizationServerUri = new Uri(Paths.AuthorizationServerBaseAddress);
        var authorizationServer = new AuthorizationServerDescription
        {
            AuthorizationEndpoint = new Uri(authorizationServerUri, Paths.AuthorizePath),
            TokenEndpoint = new Uri(authorizationServerUri, Paths.TokenPath)
        };
        _webServerClient = new WebServerClient(authorizationServer, Clients.Client1.Id, Clients.Client1.Secret);
    }

    private static void RequestToken()
    {
        var state = _webServerClient.GetClientAccessToken(new[] { "bio", "notes" });
        _accessToken = state.AccessToken;
    }

    private static void AccessProtectedResource()
    {
        var resourceServerUri = new Uri(Paths.ResourceServerBaseAddress);
        var client = new HttpClient(_webServerClient.CreateAuthorizingHandler(_accessToken));
        var body = client.GetStringAsync(new Uri(resourceServerUri, Paths.MePath)).Result;
        Console.WriteLine(body);
    }
}

```

**Comment by AArnott** [comment]
Your use of `Task.Result` is what's causing the deadlock. You should be using `await` instead of `Result` because otherwise you defeat async and make your server take up extra threads to respond to a single request. The ASP.NET SynchronizationContext only allows the use of one thread per request, so when you use `Result` it hangs.

Try using `await` instead.
