### ISSUE TITLE
Add debugging symbols to Nuget Packages

### ISSUE THREAD

**Issue by Mansfield7** [DotNetOpenAuth/DotNetOpenAuth#334]
According to this issue: https://github.com/DotNetOpenAuth/DotNetOpenAuth/issues/60, debugging symbols were added to the nuget packages, but they don't seem to include them now (neither the unified nor individual packages). If these could be added it would be a big help.

**Comment by AArnott** [comment]
They are in the NuGet packages. But nuget.org doesn't host those packages. NuGet creates packages twice -- once with symbols and once without. The ones with symbols go to symbolsource.org. You can visit there to read about how to configure VS to automatically download symbols on demand and even get the matching source code so you can step through.
