### ISSUE TITLE
await GetStringAsync(uri) doesn't work

### ISSUE THREAD

**Issue by CRogala** [DotNetOpenAuth/DotNetOpenAuth#345]
I have a WPF application (testing app) and an MVC Web API.  The client application is using a resource owner password credential grant to authenticate the user, and everything works just fine with the authentication process.  When I make the call below, the application get hung up.

//Pretty much the same example that is provided
string b= await client.GetStringAsync(_resourceUri); 

or 

//My preferred method of making the call
HttpResponseMessage r= await client.GetAsync(_resourceUri); 

I added a break point in the Web API, and it's making it to the Web API with the correct user.  I made sure the call to the database was returning a result by serializing (JSON) the result into a local variable before returning the local variable.

I was able to get this to work by doing the following:

string b = client.GetStringAsync(_resourceUri).Result;

But this removes the async functionality needed to run this in the background.

**Comment by DavidChristiansen** [comment]
You appear to be using the alpha release of v5.  I would downgrade to the last stable release 

```
PM> Install-Package DotNetOpenAuth -Version 4.3.4.13329
```
