### ISSUE TITLE
Missing Credit

### ISSUE THREAD

**Issue by tomap** [DotNetOpenAuth/DotNetOpenAuth#384]
Hi,

In your credit, you forgot to mention that you are using Mentalis Content from 
http://www.mentalis.org

License is here http://www.mentalis.org/site/license.qpx
and should/could be included?

Regards,

Thomas

**Comment by AArnott** [comment]
Hi @tomap. It appears your right. 
Changes to this project are quite slow nowadays. Can you help us out either with a PR or letting us know where you would expect the credit? In our copyright file, perhaps?

**Comment by tomap** [comment]
Thank you
