### ISSUE TITLE
The message expired

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [DotNetOpenAuth/DotNetOpenAuth#42]
DotNetOpenAuth 4.0.0.11165

The Message expired at 7/2/2011 5:23:50 PM and it is now 7/2/2011 5:36:29 PM.

  Works locally(cassini), fails deployed. Tried using the example from http://www.dotnetopenauth.net/developers/code-snippets/configuration-options/  
privateSecretMaximumAge="07:00:00"
but the attribute wasn't recognized.

Server is Microsoft Windows NT 6.0.6002 Service Pack 2 (32 bit)
Microsoft-IIS/7.0

**Comment by AArnott** [comment]
Can you please provide more context?  What type of message was this?  What protocol?  Any surrounding logs would also be helpful.

**Comment by ImaginaryDevelopment** [comment]
With both yahoo, and google, not sure what all you would like or how to go about getting much more information.

**Comment by AArnott** [comment]
Whether you're talking about OpenID vs. OAuth would be useful.  Have you checked your machine's clock against an official source to make sure you're reasonably in sync?

**Comment by ImaginaryDevelopment** [comment]
how can I tell if it's openID or OAuth?

I'm using
https://github.com/ImaginaryDevelopment/Html5OpenIdTemplate/tree/master/AppBase/App

**Comment by AArnott** [comment]
If your operation is to log in via Google or Yahoo, then that's OpenID.  It
seems like a clockskew issue.  Can you please check the clock on your
deployed server?

**Comment by ImaginaryDevelopment** [comment]
And now I suspect it was my host, as I sent them an email asking about the server time yesterday, and today the login is working fine.

**Comment by ImaginaryDevelopment** [comment]
UtcNow returns:

server Sunday, July 03, 2011;5:40:09 PM.
 locally run
Sunday, July 03, 2011;5:38:39 PM

when the requests are sent within a second of each other.

**Comment by AArnott** [comment]
That should be a tolerable difference.

Sent from my Windows Phone From: ImaginaryDevelopment
Sent: Sunday, July 03, 2011 10:47 AM
To: andrewarnott@gmail.com
Subject: Re: [dotnetopenid] The message expired (#42)
UtcNow returns:

server Sunday, July 03, 2011;5:40:09 PM.
 locally run
Sunday, July 03, 2011;5:38:39 PM

when the requests are sent within a second of each other.

On Sun, Jul 3, 2011 at 10:52 AM, AArnott <
reply@reply.github.com>wrote:

> If your operation is to log in via Google or Yahoo, then that's OpenID.  It
> seems like a clockskew issue.  Can you please check the clock on your
> deployed server?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AArnott/dotnetopenid/issues/42#issuecomment-1493336

##
