### ISSUE TITLE
Allow OAuth Authentication info to be passed via HTTP Authentication header

### ISSUE THREAD

**Issue by IDispose** [DotNetOpenAuth/DotNetOpenAuth#46]
The current implementation of sending a GET request passes the OAuth authentication info via query string parameters. Not all api's accept this, most notably FitBit.com 

Please provide an option so that the OAuth information can be sent via an Authentication HTTP header.

thanks

**Comment by AArnott** [comment]
There is already such an option in dotnetopenauth.  Simply include the appropriate flag (HttpDeliveryMethods.AuthorizationHeaderRequest) to the MessageReceivingEndpoint constructor.

**Comment by IDispose** [comment]
Sorry. I did not comprehend the documentation on MessageEndPoint flags and so was not using the API correctly. Just had to pass an OR list of options to the MessagingEndPoint. Can confirm that it works just like I expect it to. 

Thanks for the quick response.
