### ISSUE TITLE
DotNetOpenAuth not FIPS compliant

### ISSUE THREAD

**Issue by joeudwin** [DotNetOpenAuth/DotNetOpenAuth#47]
Unfortunately DotNetOpenAuth is using hashing algorithms that are not FIPS compliant (e.g SHA512Managed).
This means that DotNetOpenAuth will throw an error / not run on servers that enforce the FIPS policy.

<b>More Info:</b>
System.Security.Cryptography.SHA512Managed is not part of the Windows Platform FIPS-validated cryptographic algorithms.
http://msdn.microsoft.com/en-us/library/system.security.cryptography.sha512managed.sha512managed.aspx 

You can test this by enforcing FIPS compliance on your machine:
Run C:\Windows\System32\secpol.msc
Enable Security Settings\Local Policies\Security Options\System cryptography: Use FIPS 140 compliant cryptographic algorithms, including encryption, hashing and signing algorithms

And then run the code (These SHA classes are used by 'DotNetOpenAuth.OpenId.HmacShaAssociation’):

try { var a = new SHA512Managed(); }
catch (Exception e) { Console.WriteLine(e); }

try { var a = new HMACSHA512(); }
catch (Exception e) { Console.WriteLine(e); }

<b>Solution:</b>

Use a FIPS compliant SHA algorithm
e.g SHA512Cng
http://msdn.microsoft.com/en-us/library/system.security.cryptography.sha512cng.aspx 

Most government organisations are now implementing FIPS policies so this would be a good thing to fix. 

<b>Error:</b>

System.TypeInitializationException:The type initializer for 'DotNetOpenAuth.OpenId.HmacShaAssociation' threw an exception.
   at DotNetOpenAuth.OpenId.HmacShaAssociation.Create(Protocol protocol, String associationType, AssociationRelyingPartyType associationUse, ProviderSecuritySettings securitySettings)
   at DotNetOpenAuth.OpenId.ChannelElements.SigningBindingElement.GetDumbAssociationForSigning()
   at DotNetOpenAuth.OpenId.ChannelElements.SigningBindingElement.GetAssociation(ITamperResistantOpenIdMessage signedMessage)
   at DotNetOpenAuth.OpenId.ChannelElements.SigningBindingElement.ProcessOutgoingMessage(IProtocolMessage message)
   at DotNetOpenAuth.Messaging.Channel.ProcessOutgoingMessage(IProtocolMessage message)
   at DotNetOpenAuth.Messaging.Channel.PrepareResponse(IProtocolMessage message)
   at DotNetOpenAuth.OpenId.Provider.OpenIdProvider.PrepareResponse(IRequest request)
   … in 
System.InvalidOperationException:This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA512Managed..ctor()
   at DotNetOpenAuth.OpenId.HmacShaAssociation..cctor()

**Comment by AArnott** [comment]
This is great feedback, thank you.  

I wonder if `SHA256.Create()` would be a sufficient change.  It seems like it should ideally create either Sha256Cng or Sha256Managed as supported and appropriate.  Do you know if that would work?

**Comment by hazzik** [comment]
@joeudwin 
`SHA256.Create()` depends on configuration provided to application, see http://msdn.microsoft.com/en-us/library/693aff9y.aspx

**Comment by AArnott** [comment]
So couldn't a web.config file contain the necessary settings to make the library FIPS-compliant if the library called the SHA256.Create() method?

**Comment by hazzik** [comment]
@AArnott
I think it could

**Comment by joeudwin** [comment]
Good spot @hazzik.
There is good and bad news...

I can get SHA512.Create() to work by modifying the machine.config

However annoyingly it seems HMACSHA1 is the only FIPS compliant implementation built into .Net out of the ones you are using:
HMACSHA512,HMACSHA384,HMACSHA256 and HMACSHA1.
I will search for another source for these algorithms and report back.

**Comment by joeudwin** [comment]
After doing some research i have found that the CLR Security team have created FIPS compliant versions of the other HMAC algorithms in the <a href="http://clrsecurity.codeplex.com/">clrsecurity codeplex project</a> (<a href="http://blogs.msdn.com/b/shawnfa/archive/2008/07/10/clr-security-team-codeplex-site.aspx">see blog</a>)
After adding the <a href="http://clrsecurity.codeplex.com/releases/view/47764">Security.Cryptography.dll</a> to the bin folder and adding the following section to the machine config

&lt;mscorlib&gt;
    &lt;cryptographySettings&gt;  
      &lt;cryptoNameMapping&gt;
        &lt;cryptoClasses&gt;
          &lt;cryptoClass TestSHA512=&quot;System.Security.Cryptography.SHA512Cng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;/&gt;
      &lt;cryptoClass TestHMACSHA512=&quot;Security.Cryptography.HMACSHA512Cng, Security.Cryptography, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot;/&gt;
        &lt;/cryptoClasses&gt;  
        &lt;nameEntry name=&quot;System.Security.Cryptography.SHA512&quot; class=&quot;TestSHA512&quot;/&gt;
        &lt;nameEntry name=&quot;HMACSHA512&quot; class=&quot;TestHMACSHA512&quot;/&gt;
      &lt;/cryptoNameMapping&gt;
    &lt;/cryptographySettings&gt;
  &lt;/mscorlib&gt;

I can get of the following lines to work without error:

var a = SHA512.Create();
var b = HMAC.Create("HMACSHA512");

So i think the code changes needed to make dotNetOpenAuth work with the FIPS policy enforced is as simple as replacing the use of 
new SHA512Managed() with SHA512.Create(); 
and
new HMACSHA512() with HMAC.Create("HMACSHA512");

**Comment by AArnott** [comment]
Stellar.  Thanks.  We should be able to get this into the next release.

**Comment by joeudwin** [comment]
That is great news! When is the next release scheduled for? 
Will you update this issue when it is resolved?

**Comment by AArnott** [comment]
There isn't a schedule for it right now.  Hopefully in the next month.  And yes, this issue will be updated when that happens.

**Comment by joeudwin** [comment]
Hi @AArnott, any update on when this may be fixed/ released?
Thanks!

**Comment by tonyrsmith** [comment]
Hi @AArnott, I would also be interested in this fix any idea when it might be ready?  Thanks.

**Comment by AArnott** [comment]
We're looking at a release by the end of this month.  I hope this issue can be fixed there.

**Comment by AArnott** [comment]
This has been fixed in 72f107fd.  Slated for release in the coming week.

**Comment by AArnott** [comment]
HMACSHA algorithms still need to be converted.
