### ISSUE TITLE
Decrypting access token requires request message not exposed by ResourceServer

### ISSUE THREAD

**Issue by oyvindkinsey** [DotNetOpenAuth/DotNetOpenAuth#49]
When using the ResourceServer to verify access to a resource, `VerifyAccess` leads to an instance of `OAuthPrincipal` containing the provided scopes as roles internally.

If one wants access to the list of scopes this is not directly available, and you are forced to use the `StandardTokenAnalyzer` directly, but this requires an `IDirectedProtocolMessage`, which is not available from the ResourceServer.

**Propositions**
- Alternative 1
  Set a GenericPrincipal instead of an OAuthPrincipal and also return the deserialized Access Token.
  This way we can wrap this in a custom principal if we choose, exposing both the client id as well as other data about the token.
- Alternative 2
  Provide a GetRequest on the ResourceServer that returns the IDirectedProtocolMessage used to check the access.

**Comment by AArnott** [comment]
This is fixed now by virtue of the AccessToken being available to the resource server host now as an out parameter from `VerifyAccess`.

**Comment by oyvindkinsey** [comment]
Great - if I remember correctly I had to turn to reflection in order to extract the roles from the `OAuthPrincipal` so as instantiate a new `GenericPrincipal`.
