### ISSUE TITLE
Signature Generation Sample

### ISSUE THREAD

**Issue by tlianza** [DotNetOpenAuth/DotNetOpenAuth#57]
From looking through the code and tests, it seems there's no way to generate a signature that's decoupled from the process of running a service endpoint.  Am I missing it?  

I'm looking for something in the neighborhood of this (which I'll probably continue using, but wanted a 'second opinion' on some character encoding issues):

http://oauth.googlecode.com/svn/code/csharp/OAuthBase.cs

This is a straightforward one-file library with a single method to generate the signature.

Thanks!

**Comment by AArnott** [comment]
What is the scenario behind why you want to generate signatures for anything other than outgoing or incoming network requests?

**Comment by tlianza** [comment]
In my case I'm using MVC to handle the requests, and it's designed in such a way that it can handle requests from a website (people logged-in with regular forms-based auth) and OAuth-based requests. So, I'm handling the incoming network requests myself so that I can re-use the same actions in both places (somewhat similar to how you'd use ActiveResource in Rails).

**Comment by AArnott** [comment]
That sounds good.  Using the same actions regardless of authorization method is definitely a good idea.  It seems that an HTTP authorization module (or whatever the MVC-friendly equivalent is) would be an appropriate fit here.  For instance, one of the DNOA samples includes an OAuth HTTP authorization module that works in conjunction with the module that does forms based auth.  Yet no custom signature method was needed -- just what DNOA offered out of the box.

**Comment by AArnott** [comment]
Closing due to non-response.
