### ISSUE TITLE
Adding an artifact for DiffieHellman-free assemblies

### ISSUE THREAD

**Issue by ghost** [DotNetOpenAuth/DotNetOpenAuth#85]
As per discussion via email, please add an artifact to build job to produce a version of OpenId.Core package/assembly that doesn't include the two dependency assemblies Mono.Math and Org.Mentalis.Security.Cryptography. We (the asp.net) team can't ship those in the box, and we want to reduce the total assembly size of the installer MSI too.

**Comment by AArnott** [comment]
Fixed by b8b3c1cf15
