### ISSUE TITLE
problems building +build.$(BuildNumber).$(GitCommitId.Substring(0,10))

### ISSUE THREAD

**Issue by mikebz** [DotNetOpenAuth/DotNetOpenAuth#88]
I am getting errors when I build the source in VS.NET 2010.
I can yank these GitCommitId references out but I wanted to make sure that there isn't a simple resolution to it first.

Here is the build log.

------ Rebuild All started: Project: Mono.Math, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.Core, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: Org.Mentalis.Security.Cryptography, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.OAuth.Common, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.OAuth2, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.OAuth, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.InfoCard, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.Core.UI, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.OAuth2.Client, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.OAuth.Consumer, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.OAuth.ServiceProvider, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.OAuth2.AuthorizationServer, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: DotNetOpenAuth.InfoCard.UI, Configuration: Debug Any CPU ------
C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4): error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated. Index and length must refer to a location within the string. Parameter name: length
------ Rebuild All started: Project: RelyingPartyDatabase, Configuration: Debug Any CPU ------

**Comment by AArnott** [comment]
Ah, interesting.  Thanks for reporting this.  Did you download the source
code as a zip file, such that there is no git repository?

On Monday, March 12, 2012, Mike Borozdin wrote:

> I am getting errors when I build the source in VS.NET 2010.
> I can yank these GitCommitId references out but I wanted to make sure that
> there isn't a simple resolution to it first.
> 
> Here is the build log.
> 
> ------ Rebuild All started: Project: Mono.Math, Configuration: Debug Any
> CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.Core, Configuration:
> Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: Org.Mentalis.Security.Cryptography,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.OAuth.Common,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.OAuth2, Configuration:
> Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.OAuth, Configuration:
> Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.InfoCard,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.Core.UI,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.OAuth2.Client,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.OAuth.Consumer,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.OAuth.ServiceProvider,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project:
> 
> ## DotNetOpenAuth.OAuth2.AuthorizationServer, Configuration: Debug Any CPU
> 
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: DotNetOpenAuth.InfoCard.UI,
> Configuration: Debug Any CPU ------
> C:\Users\Administrator\Desktop\AArnott-dotnetopenid-6c29eba\tools\DotNetOpenAuth.Versioning.targets(29,4):
> error MSB4184: The expression """.Substring(0, 10)" cannot be evaluated.
> Index and length must refer to a location within the string. Parameter
> name: length
> ------ Rebuild All started: Project: RelyingPartyDatabase, Configuration:
> Debug Any CPU ------
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AArnott/dotnetopenid/issues/88

## 

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by mikebz** [comment]
yes, I just got the zip (running windows in a VM - my main box is a Mac), but I can install Git on my virtual machine and try again..

**Comment by AArnott** [comment]
Ok, thanks. it seems likely that the build system just doesn't support
running without the project having been downloaded within a git repo, but
it's probably an easy fix, and one that should be made.

And yes, in the meantime using git to download the project should unblock
you.

On Monday, March 12, 2012, Mike Borozdin wrote:

> yes, I just got the zip (running windows in a VM - my main box is a Mac),
> but I can install Git on my virtual machine and try again..
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AArnott/dotnetopenid/issues/88#issuecomment-4465481

## 

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by mikebz** [comment]
Andrew, building from the github seems to solve that issue.  Thanks!

**Comment by AArnott** [comment]
Reopening so we can fix the build to not require a git repo.
