### ISSUE TITLE
Projects default to .NET 3.5 while it looks like they need 4.0

### ISSUE THREAD

**Issue by mikebz** [DotNetOpenAuth/DotNetOpenAuth#89]
A bunch of projects need libraries like System.Xaml which are in 4.0

(http://social.msdn.microsoft.com/Forums/en-US/csharpgeneral/thread/c281e42a-445f-4ef4-b3e8-032efb1a9297/)

It's not a huge deal to fix it, but I thought I'd let you know that by default VS.NET 2010 opens all of the projects in the solution with the default to 3.5.

**Comment by mikebz** [comment]
the libraries are not an issue when using MSBuild closing the issue.

**Comment by AArnott** [comment]
It's also not an issue when building within VS.  C# just shows all references in the IDE regardless of their Condition.  So the build authoring will include the right references when targeting each version of the framework.

**Comment by mikebz** [comment]
you are right, I switched to just using msbuild and got much further.  thanks!
