### ISSUE TITLE
Infocardselector doesnt work with Firefox and IdentitySelector

### ISSUE THREAD

**Issue by philippjenni** [DotNetOpenAuth/DotNetOpenAuth#9]
When use Firefox and IdentitySelector (http://identityselector.codeplex.com) then displays the infocardselector control only an "undefined" message at the top of the page. There is no object tag in header definied.

**Comment by philippjenni** [comment]
The Problem is in the JavaScript. OuterHTML is not supported in Firefox. There is use a help funktion to write the object tag to the page

**Comment by DavidChristiansen** [comment]
Infocard is no longer an active project.
