### ISSUE TITLE
errors in DotNetOpenAuth.Messaging.StandardWebRequestHandler.GetResponse when deploying to a locked down server

### ISSUE THREAD

**Issue by mikebz** [DotNetOpenAuth/DotNetOpenAuth#90]
We are trying to deploy a solution that includes DNOA to a locked down environment and we are getting errors (trace included below).  

Question: can this be mitigated without turning off the 
<servicePointManager checkCertificateRevocationList="true"/>

Is this even the same issue?

```
Source:
DotNetOpenAuth


Stack Trace:
at
DotNetOpenAuth.Messaging.StandardWebRequestHandler.GetResponse(HttpWebReque
st request, DirectWebRequestOptions options)
  at
DotNetOpenAuth.Messaging.StandardWebRequestHandler.GetResponse(HttpWebReque
st request)
  at DotNetOpenAuth.Messaging.Channel.GetDirectResponse(HttpWebRequest
webRequest)
  at
DotNetOpenAuth.Messaging.Channel.RequestCore(IDirectedProtocolMessage
request)
  at DotNetOpenAuth.Messaging.Channel.Request(IDirectedProtocolMessage
requestMessage)
  at
DotNetOpenAuth.OAuth2.ClientBase.UpdateAuthorizationWithResponse(IAuthoriza
tionState authorizationState, EndUserAuthorizationSuccessAuthCodeResponse
authorizationSuccess)
  at DotNetOpenAuth.OAuth2.UserAgentClient.ProcessUserAuthorization(Uri
actualRedirectUrl, IAuthorizationState authorizationState)
```

**Comment by AArnott** [comment]
I couldn't say whether it's the same issue without knowing the exception
type and message that was thrown. You included the stack trace in your
original report, but omitted the type and message.

**Comment by mikebz** [comment]
I am currently just getting the event log view of the server can't attach via a debugger.  Everything works fine on the dev box.

Here is the error eventlog reports:

Error: Error occurred while sending a direct message or getting the response.

**Comment by AArnott** [comment]
There should be an InnerException within that exception that contains more detail.  Enabling logging (http://tinyurl.com/dnoalogs) would also likely reveal the underlying failure.

**Comment by AArnott** [comment]
Closing due to lack of additional information.
