### ISSUE TITLE
Improve how ResourceServer.VerifyAccess reports and handles errors

### ISSUE THREAD

**Issue by bloudraak** [DotNetOpenAuth/DotNetOpenAuth#93]
Consider the following code in a custom WCF ServiceAuthorizationManager implementation to verify the token.

```
var signing = CreateAuthorizationServerSigningServiceProvider();
var encrypting = CreateResourceServerEncryptionServiceProvider();
var resourceServer = new ResourceServer(new StandardAccessTokenAnalyzer(signing, encrypting));
IPrincipal principal;
var error = resourceServer.VerifyAccess(httpDetails, requestUri, out principal);
return error != null;
```

This is rather difficult to determine what errors occurred in the call to VerifyAccess.  I'd rather like to see a method return the principal and null if verification failed.  It may be better if exceptions are thrown because one can encapsulate the error and handle it accordingly.

**Comment by AArnott** [comment]
Returning null, or throwing, would leave the host to determine how to respond to the HTTP request. Yet the OAuth 2 spec requires certain responses including specific HTTP headers in the error response, so this way that work is in the library.

Please re-open if you disagree.

**Comment by bloudraak** [comment]
My problem with current approach is that the framework hides any exception and there is no real opportunity to handle the error appropriately. It would be akin to opening a file in .NET and all the framework told you was "sorry, you can't access it" when perhaps the attached drive could not be found, or that it was locked by another process.  That would be considered poor error handling by the framework.

Because the inputs originate from outside, errors can a result of almost anything. If one understood the exact nature of the problem, one can build patterns and determine how to best support it, or take steps to protect the system if the requests are considered to be malicious. 

I'd rather have the framework tell me exactly why authorization failed, like the access token expired, issues with the signing or encryption keys, client could not be found, database access failed etc, so I can handle it appropriately according to business and security requirements.  I'd be happy to pass that exception on to another method that can build and return the appropriate response as per the spec.  

We can reopen the case if you think I have a point, otherwise, lets discuss this further at the groups and see what others think.

**Comment by AArnott** [comment]
Maybe we can throw an exception which you can "handle" then pass to another DNOA method then that will prepare the response message, as I think you suggested.

**Comment by bloudraak** [comment]
Yes, that would work. The code that comes to mind may look as follows:

``` C#
try
{
  var signing = CreateAuthorizationServerSigningServiceProvider();
  var encrypting = CreateResourceServerEncryptionServiceProvider();
  var resourceServer = new ResourceServer(new StandardAccessTokenAnalyzer(signing, encrypting));
  IPrincipal principal = resourceServer.VerifyAccess(httpDetails, requestUri);
  // evaluate the principal
  // if needed, check if the principal has access to the resource
  return true;
}
catch(OAuthException ex)
{
  // look at the inner exception for reason 
  // handle it appropriately 
  // return the appropriate response. 
}

```

I would suggest to wrap all exceptions thrown with a OAuthException so that it is easier to differentiate between issues originate from dotnetopenauth and others.  For example, I wouldn't like to handle OperationInvalidException and try to figure out whether that came from OAuth, database or WCF.

**Comment by AArnott** [comment]
Working on it now.

Ticket #122 https://github.com/AArnott/dotnetopenid/issues/122 tracks

## this.

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

On Tue, Apr 17, 2012 at 10:39 AM, Werner Strydom <
reply@reply.github.com

**Comment by AArnott** [comment]
Fixed
